### ISSUE TITLE
ExternallyVisibleError

### ISSUE THREAD

**Issue by isaachinman** [anthonyjgrove/react-google-login#10]
This warning might be coming about because of my particular usage, but it looks like it might have to do with the way `gapi` is being initialised inside the `GoogleLogin` component itself:

    Uncaught gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().

**Comment by anthonyjgrove** [comment]
I have seen this error randomly but have not be able to reproduce it.  Do you have repo steps and does it keep you from authenticating?

**Comment by isaachinman** [comment]
No, it doesn't prevent authentication, it's just a warning. My implementation is more or less identical to the docs, maybe it's environment specific. I'll see if I can set up a jsFiddle.

Surely it's just a matter of heeding the warning itself, though? Do you call `gapi.auth2.init()` or `gapi.auth2.getAuthInstance()` in the source code?

**Comment by anthonyjgrove** [comment]
It uses both. It sounds like it is calling `gapi.auth2.init()` when it shouldn't be or is called with different options.  Let me know if you can give me repo steps or a link to so we can figure out the scenario which the error is occurring.

**Comment by isaachinman** [comment]
Sure, do you have a demo `clientId` to use?

**Comment by isaachinman** [comment]
Ah, I see you've got one in the demo. In that case, here's my implementation:

    <GoogleLogin
                    style={styles.googleBtn}
                    buttonText='Login with Google'
                    callback={this.handleGoogleLogin}
                    clientId='658977310896-knrl3gka66fldh83dao2rhgbblmd4un9.apps.googleusercontent.com'
                    cssClass='btn btn-block btn-lg btn-default'
                  />

**Comment by isaachinman** [comment]
Basically, it looks like it's happening because your source code is trying to init gapi twice. If I hard reload the page and am not logged into Google, everything looks good. Then I log in. From this point onwards, anytime that component is rerendered it produces the error because it keeps trying to init gapi.

**Comment by anthonyjgrove** [comment]
Can you host it somewhere? With it showing the issue.  I have a hosted implementation here but it does not show the error: http://reactstarter.founderstack.io/register

**Comment by anthonyjgrove** [comment]
It needs Init, if you are not auth'd yet.  So it is happening when you hit that page even though you already authenticated? I guess I need a way to check if auth'd before calling init()

**Comment by isaachinman** [comment]
Did you mean to link to that registration page...?

It's hard to host this kind of stuff, jsFiddle and requirebin don't suffice and don't support ES6/npm.

Basically what you're saying is right; you need to check `gapi.auth2.getAuthInstance()` before calling `gapi.auth2.init()`. Should be a simple fix, also happy to submit a PR.

**Comment by anthonyjgrove** [comment]
I am traveling right now so wouldn't be able to look at the PR until next weekend but would be great if you could submit one for this.

**Comment by isaachinman** [comment]
Sure, but what port do you use for local testing? Tried booting the project up on 3000 and got the `redirect_uri_mismatch` error. Need to know exactly what you've specified the origin to be in your google dev console.

**Comment by anthonyjgrove** [comment]
Would have to look.  Just use your own clientId.

**Comment by isaachinman** [comment]
I addressed this in #12.
