### ISSUE TITLE
login popup is not automatically closing after clearing cookies.

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [anthonyjgrove/react-google-login#100]
@anthonyjgrove I've just got a new error. Actually this is happening when I'm using google login in default browser of redmi or iphone . After clearing cookies it's just not auto closing the OAuth pop up once authentication was done. Can you look into that what could be the problem? Though, it is running good in any other browsers.

**Comment by Abhijeetjaiswalit** [comment]
@anthonyjgrove still waiting for your response.

**Comment by john1jan** [comment]
Can you give us the steps to reproduce ?

**Comment by anthonyjgrove** [comment]
@Abhijeetjaiswalit please provide an example so we can try to reproduce it.
