### ISSUE TITLE
multiple scope 

### ISSUE THREAD

**Issue by tuannn-viosoft** [anthonyjgrove/react-google-login#103]
hi all, 

i don't know how to setup multiple scopes for login request.

example for send email scope,
```
<GoogleLogin className="btn btn-lg btn-danger btn-block"
    scope="https://www.googleapis.com/auth/gmail.send"
    clientId={googleClientID}
    onSuccess={this.googleLoginSuccess}
    onFailure={this.googleLoginFail}
/>
```
how can add read-only scope to the request.
thanks.

**Comment by tuannn-viosoft** [comment]
i try scope like this, but it doesn't work.
`scope="https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly"`

**Comment by Samtaro** [comment]
Have you figured out a way?

I've tried 

`scope={[
    'https://www.googleapis.com/auth/yt-analytics.readonly',
    'https://www.googleapis.com/auth/youtubepartner-channel-audit'
 ]}`

`scope={
    'https://www.googleapis.com/auth/yt-analytics.readonly,
    https://www.googleapis.com/auth/youtubepartner-channel-audit'
 }`

Neither work.

**Comment by Samtaro** [comment]
Figured it out.

`                <GoogleLogin
                  className='u-hide'
                  clientId={config.googleId}
                  onSuccess={this.googleResponse}
                  onFailure={this.googleResponse}
                  scopes={['yt-analytics.readonly', 'youtubepartner-channel-audit']}
                  ref='google'
                />`
