### ISSUE TITLE
React 15.x.x - Build errors

### ISSUE THREAD

**Issue by danielg2002** [anthonyjgrove/react-google-login#115]
Are you really need React 16 in this component?

I suggest create a version 3 of your component with the new requirement, because there are many projects using React 15.x.x and for a period of time will be imposible migrate to React 16.

Currently I'm using React 15.6.1 and multiple issues arrives if i migrate to the last version of your component.

**Comment by john1jan** [comment]
You can just go to your **node_modules** and change react version and use the component. there is no change in code level in this component

**Comment by anthonyjgrove** [comment]
Use version 2.10.x for React 15.x
