### ISSUE TITLE
"One moment please..." when login.

### ISSUE THREAD

**Issue by vuuet** [anthonyjgrove/react-google-login#116]
I got a message "One moment please..." when clicking to the login button. And it stuck on that screen. This issue appears when login with iPhone in Australia. Maybe it doesn't belong to this component, but anyone knows about that, please help me? Thank you!
https://drive.google.com/file/d/0B5q4GuigFwLPa0xqeDhUbUxqRzQ/view?usp=sharing

**Comment by liywjl** [comment]
We have been getting a similar issue, it appears to be affect iOS devices 9 & 10 when using the in-app browser. Using mobile Safari (not the in-app browser) seems to resolve the issue, but this still needs to be fixed for us.

**Comment by sudhiryadav** [comment]
I am using version 3.0.10 and am also having same issue.

**Comment by sudhiryadav** [comment]
could this be an issue while i try to use this library in the in app browser of facebook ? 
https://github.com/Azure/azure-mobile-apps-ios-client/issues/90

**Comment by Nitro1231** [comment]
Does anyone know how to fix this issue?

**Comment by axmedbek** [comment]
I have too same issue
