### ISSUE TITLE
file://apis.google.com/js/client:platform.js net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by bras1223** [anthonyjgrove/react-google-login#119]
When I run my app in developer-mode, the GoogleLogin works.
But when trying to build the app, the button gets disabled and console logs this;
`GET file://apis.google.com/js/client:platform.js net::ERR_FILE_NOT_FOUND`

Shouldn't `js.src = '//apis.google.com/js/client:platform.js'` be `js.src = '**https:**//apis.google.com/js/client:platform.js'`?

**Comment by sn1ff** [comment]
Same problem here when running the code on a mobile device.
