### ISSUE TITLE
Typo in documention for GoogleLogout success callback should be onSuccess instead of onLogoutSuccess

### ISSUE THREAD

**Issue by TommieEdwardBerry** [anthonyjgrove/react-google-login#121]
The documentation shows 👍 
```js
    import GoogleLogout from 'react-google-login';
    <GoogleLogout
      buttonText="Logout"
      onLogoutSuccess={logout}
    >
    </GoogleLogout>
  ```

but should be onSuccess or you get a runtime error:

cb=gapi.loaded_0:79 Uncaught TypeError: this.props.onSuccess is not a function
    at t.value (google-login.js:1)
    at google-login.js:1
    at h.r2 (cb=gapi.loaded_0:87)
    at xs (cb=gapi.loaded_0:90)
    at Wq (cb=gapi.loaded_0:90)
    at _.C.uea (cb=gapi.loaded_0:89)
    at Ap (cb=gapi.loaded_0:83)
    at <anonymous>

I think you forgot to rename the callback on the logout.

**Comment by john1jan** [comment]
@TommieEdwardBerry the example is working fine. And more over 
**onLogoutSuccess** is the right property which is used internally

**Comment by john1jan** [comment]
If you pass **onSuccess** you will get a runtime error. Don't pass **onSuccess** in GoogleLogout pass **onLogoutSuccess** as props

**Comment by john1jan** [comment]
Closing this for. You can reopen it if you still face the same problem

**Comment by TommieEdwardBerry** [comment]
Here  is my code using the create-react-app and editing app.js to look like below.
It works fine, as long as I use the parameter name onSuccess
if I use onLogoutSuccess  then it never calls my inline function to setState when I log out.
When it works, it askes which account to logout, which is different then other implementations.


import React, { Component } from 'react';
import logo from './logo.svg';
import GoogleLogin from 'react-google-login';
import GoogleLogout from 'react-google-login';
import './App.css';

class App extends Component {
  constructor(props){
      super(props);
      this.state = { isLoggedIn: "" }
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>

        {((this.state.isLoggedIn==="false") || (this.state.isLoggedIn==="")) ?
        <div>
          <GoogleLogin
            clientId="997712837338-gom1560gihib417pqpl237hmbp2aqdio.apps.googleusercontent.com"
            buttonText="Login" 
            onSuccess={(response) => { this.setState(()=>{return { isLoggedIn: "true"  }})}} 
            onFailure={(response) => { this.setState(()=>{return { isLoggedIn: "false" }})}}>
          </GoogleLogin>
        </div>
        :
        <div>
            <GoogleLogout 
              clientId="997712837338-gom1560gihib417pqpl237hmbp2aqdio.apps.googleusercontent.com"
              buttonText="Logout" 
              onSuccess={(response) => { this.setState(()=>{return { isLoggedIn: "false" } } ) } } >
            </GoogleLogout>
        </div>
      }
      </div>
    );
  }
}
export default App;

**Comment by john1jan** [comment]
@TommieEdwardBerry i saw your code. You are using it wrong. You should use
 **onSuccess** in **GoogleLogin** and
**onLogoutSuccess** in **GoogleLogout** 

Example
```
<GoogleLogin
    clientId="658977310896-knrl3gka66fldh83dao2rhgbblmd4un9.apps.googleusercontent.com"
    buttonText="Login"
    onSuccess={responseGoogle}
    onFailure={responseGoogle}
  />
```
```
 
<GoogleLogout
      buttonText="Logout"
      onLogoutSuccess={logout}
    >
```

**Comment by TommieEdwardBerry** [comment]
If I put onLogoutSuccess it does not log out.
Tommie

**Comment by dipugm** [comment]
Any resolution on this? onLogoutSuccess gets called only if I logout from the same tab as the one I logged in. If I refresh that tab, boom, logout does not work. No information of any sort.

**Comment by TommieEdwardBerry** [comment]
No, I worked around it by writing my own logout routine that kills the google objects.

On Mar 28, 2018, at 4:46 AM, Deepak Mariyappa <notifications@github.com> wrote:

Any resolution on this? onLogoutSuccess gets called only if I logout from the same tab as the one I logged in. If I refresh that tab, boom, logout does not work. No information of any sort.

**Comment by TommieEdwardBerry** [comment]
Here is the code to log out that I had to use.
=====================================
var forceMyOwnLogout = ((response) => {
            let ThisIDtoBeLoggedOUT = cookie.select(/MyGoogleID/).MyGoogleID
            cookie.remove('MyGoogleID', { path: '/' })
            axios("https://berry.org/api/tm/users.pl?SetUserLoggedIn=false&user=" + ThisIDtoBeLoggedOUT).then(
                (result) => {
                    cookie.remove('MyGoogleID', { path: '/' })
                    cookie.remove('G_AUTHUSER_H', { path: '/' })
                    this.setState({
                        "users": result.data, "cookies": cookie.loadAll(), "UsersAreLoading": false,"UserLoggedInID":0})
                })
            if (window.gapi) {
                const auth2 = window.gapi.auth2.getAuthInstance()
                if (auth2 != null) {
                    auth2.signOut().then(
                        auth2.disconnect()    //.then(this.props.onLogoutSuccess)
                    )
                }
            }
            this.forceUpdate() 
        })

**Comment by puttums6790** [comment]
Tommie did you put this in the app.js file?

**Comment by puttums6790** [comment]
@TommieEdwardBerry tommie did you put this in the app.js file?

**Comment by TommieEdwardBerry** [comment]
No, all my app.js does is render a component I named Top, which has the login and logout buttons.
