### ISSUE TITLE
GoogleLogout , onSuccess vs onLogoutSuccess, please look at the work to show you this.

### ISSUE THREAD

**Issue by TommieEdwardBerry** [anthonyjgrove/react-google-login#122]
I know you are tired of this issue, and you keep deleting it.
So I spent a lot of time to document this problem.
These two links show the GoogleLogin and GoogleLogout buttons with only one change:
       This one works:  http://berry.org/googlog
and This one does not log out : http://berry.org/googbad

There is only one line different,  onSuccess=    vs    onLogoutSuccess=
The only other difference is the 
"homepage" : "http://berry.org/googlog"   vs   "homepage" : "http://berry.org/googbad"

The app is created with create-react-app and the zip files attached have the 3 files that change
for the bad and good versions.

I attached 2 zip files with the app.css, app.js and package.js files in them.

Please help, Call me if needed,
Tommie Berry
925-980-1021

[GoodFiles.zip](https://github.com/anthonyjgrove/react-google-login/files/1385969/GoodFiles.zip)
[BadFiles.zip](https://github.com/anthonyjgrove/react-google-login/files/1385970/BadFiles.zip)

**Comment by TommieEdwardBerry** [comment]
The links above only work in Chrome.
Safari and Firefox from my iPad do not log in , even with the good one.

**Comment by john1jan** [comment]
Sure @TommieEdwardBerry will check whats the problem and let you know

**Comment by john1jan** [comment]
@TommieEdwardBerry I have figured out the issue. The issue is react-google-login npm package is not updated. We will have to change the version and publish a new version in npm package. We will do that ASAP. @anthonyjgrove Can you bump up the version and publish in npm registry asap

**Comment by john1jan** [comment]
@TommieEdwardBerry as a quick fix you go to node_modules/react-google-login/dist and replace the google-login.js to the attached file [google-login.js.zip](https://github.com/anthonyjgrove/react-google-login/files/1386250/google-login.js.zip) and change your import to 

`import { GoogleLogin, GoogleLogout } from 'react-google-login';`
Try with this and let me know if you still have the issue

**Comment by TommieEdwardBerry** [comment]
John,  (Thanks for the help)

I downloaded the zip file and put it in the directory you specified.

I changed my 2 lines for import to :

import { GoogleLogin, GoogleLogout } from 'react-google-login';

 

But I get an error using your import statement. (See error below)

 

If I put it back to:

import GoogleLogin   from 'react-google-login';

import GoogleLogout  from 'react-google-login';

 

it works as before, only when I use onSuccess ??

 

Sorry,

Tommie

 

 

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.

▶ 24 stack frames were collapsed.

./src/index.js

C:/Users/tom/React/googloger/src/index.js:7

  4 | import App from './App';
  5 | import registerServiceWorker from './registerServiceWorker';
  6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
  8 | registerServiceWorker();
  9 | 
  10 | 

View compiled

▶ 6 stack frames were collapsed.

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by anthonyjgrove** [comment]
version 3.0.0 published with logout component

**Comment by john1jan** [comment]
@TommieEdwardBerry are you still facing the issue. Its working fine for me. I will help in debug if you can share your code. Share the code with node_modules folder

**Comment by john1jan** [comment]
If you want to share it private you can email me at john1jan@gmail.com
