### ISSUE TITLE
Problems when updating to version 3

### ISSUE THREAD

**Issue by juank11memphis** [anthonyjgrove/react-google-login#124]
I keep getting this after updating to version 3.0.0, if I go back to version 2.11.3 the problem is gone.

`warning.js?6327:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

My component looks like this: 

```
<GoogleLogin
  clientId={googleClientId}
  onSuccess={onGoogleResponse}
  onFailure={onGoogleResponse}
  uxMode="popup"
>
  <Icon name="google" />
  {googleText}
</GoogleLogin>
```

**Comment by john1jan** [comment]
Change your import like this

```import { GoogleLogin } from 'react-google-login';```
