### ISSUE TITLE
Disable style boolean

### ISSUE THREAD

**Issue by efortes** [anthonyjgrove/react-google-login#126]
First of all thanks for creating this package.
Is it possible to add a `disableStyle (Boolean)` property? This way we can disable all the styles without manual editing them with `disableStyle (Object)`

**Comment by efortes** [comment]
`<GoogleLogin style={{}} />` I used an empty style prop to make it work.

**Comment by dagumak** [comment]
I think most people would expect disableStyle to be a boolean.
