### ISSUE TITLE
Error on login when used in production environment

### ISSUE THREAD

**Issue by lnmunhoz** [anthonyjgrove/react-google-login#129]
Hello, first thanks for this very handy library!

Everything is working fine on dev environment but when I build to production using webpack I am having a few issues with the `gapi` script.

The build works fine but this is throw in the console then I first load the page
```js
cb=gapi.loaded_0:75 Uncaught TypeError: a is not a function
    at google-login.js:1
    at h.o0 (cb=gapi.loaded_0:83)
    at xs (cb=gapi.loaded_0:86)
    at Wq (cb=gapi.loaded_0:86)
    at _.C.uea (cb=gapi.loaded_0:85)
    at Ap (cb=gapi.loaded_0:79)
    at <anonymous>
```

The thing is, this is not happening all the time. Sometimes it works and sometimes not. I think its possible that the function that checks if the script is loaded is not very accurate.

Any ideas?

**Comment by chhatch** [comment]
I'm having the same issue, but it is occurring in my development environment. It happens about 10% of the time in Chrome 62.0.3202.94. I have not encountered the error in Firefox 56 or 57.0.1.

**Comment by GabiAxel** [comment]
I had a similar problem with 3.0.4 always working in development and never in production, and deleting the build directory before rebuilding solved it, maybe some old code in it caused it. If it still doesn't help. maybe also try deleting node_modules and the lock file before building.

**Comment by anthonyjgrove** [comment]
please let me know if you are still experiencing this issue.

**Comment by ayualdilasalma** [comment]
I'm having the same issue when I open it on chrome 65.0.3325.181. It works fine on safari tho. I tried to rebuild the project still no luck. Please tell me how to fix this if you already know the solution. Thank you in advance

**Comment by TomPradat** [comment]
It looks like the error comes from when the gapi auth fails, the onFailure props is called but there is no default prop so the function is undefined. For a quick fix, try to provide a onFailure function to your GoogleLogin component.

After checking the doc, the onSuccess and onFailure are indeed REQUIRED props.

**Comment by japananh** [comment]
> It looks like the error comes from when the gapi auth fails, the onFailure props is called but there is no default prop so the function is undefined.
> 
> @ayualdilasalma Try to provide a onFailure function to your GoogleLogin component.
> 
> After checking the doc, the onSuccess and onFailure are indeed REQUIRED props.

I added the onFailure function but the issue still happens.

`
<GoogleLogin
                clientId="xxx.apps.googleusercontent.com"
                buttonText=""
                render={(renderProps) => (
                  <button
                    className={styles.socialButton}
                    onClick={renderProps.onClick}
                    disabled={renderProps.disabled}
                  >
                    <img
                      src="https://img.icons8.com/color/35/000000/google-logo.png"
                      alt="google-icon"
                    />
                  </button>
                )}
                onSuccess={googleResponse}
                onFailure={googleLoginError}
                cookiePolicy={"single_host_origin"}
              />
`

**Comment by lane-eb** [comment]
@TomPradat Thank you. 
My error is 
`Uncaught TypeError: b is not a function
    at google-login.js:1`
You solution works like a charm!
