### ISSUE TITLE
List of what returned values mean?

### ISSUE THREAD

**Issue by chobo2** [anthonyjgrove/react-google-login#13]
Hi

Can you post some documentation on what the return values actually mean. I followed the example and I get data like 

WE 
El:"10262112414141281913506" 
hg:Object 
wc:PG 
__proto__:Object 

I can sort of figure out what some of the stuff means but others I got no clue. I am trying to figure out what is the "offline token" that I can store in my db and compare against in the future.

**Comment by anthonyjgrove** [comment]
Sure, I will try to update it this weekend

**Comment by anthonyjgrove** [comment]
Updated readme, let me know if there needs to be more clarity in the documentation.

**Comment by chobo2** [comment]
Cool. I will look into it when I can. Switched gears for a bit and not looking at login right now.
