### ISSUE TITLE
Unable to use GoogleLogin named export in TS project

### ISSUE THREAD

**Issue by corydeppen** [anthonyjgrove/react-google-login#134]
Although the default export works fine, I get a TS error `TS2305: Module '"path/to/node_modules/react-google-login/index"' has no exported member 'GoogleLogin'` when I try to use the `GoogleLogin` named export from the latest release (3.0.2).

```ts
import { GoogleLogin } from 'react-google-login';
```

From what I've seen, and if I understand the [TS docs](http://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#needless-namespacing), I believe the change made in PR #107 to wrap members in a namespace isn't necessary.

> To reiterate why you shouldn’t try to namespace your module contents, the general idea of namespacing is to provide logical grouping of constructs and to prevent name collisions. Because the module file itself is already a logical grouping, and its top-level name is defined by the code that imports it, it’s unnecessary to use an additional module layer for exported objects.

I was able to resolve the error by removing the namespace wrapper, allowing both the `GoogleLogin` class to be exported and a default export to be defined. Would you be open to reviewing a PR?

**Comment by a-tarasyuk** [comment]
+1

**Comment by maws** [comment]
+1

**Comment by easyspeak** [comment]
+1

**Comment by anthonyjgrove** [comment]
Is there a merge request that fixes this?

**Comment by corydeppen** [comment]
I think PR #141 by @broder will resolve this.

**Comment by anthonyjgrove** [comment]
Can anyone 2nd that PR #141 will fix the issue. I am not familiar with typescript.

**Comment by yershalom** [comment]
Hi @anthonyjgrove ,

I checked this PR #141  and you have green light to publish it.

thanks

**Comment by anthonyjgrove** [comment]
@yershalom @corydeppen  

Please try react-google-login@3.0.3

**Comment by corydeppen** [comment]
@anthonyjgrove Yep, that should work. Thanks.
