### ISSUE TITLE
could you add icon property like react-facebook-login

### ISSUE THREAD

**Issue by YoungsoonLee** [anthonyjgrove/react-google-login#14]
could you add icon property like react-facebook-login?
icon="fa-facebook"

https://github.com/keppelen/react-facebook-login

**Comment by anthonyjgrove** [comment]
You can add icons, I just decided to do it in a way that is more flexible.   Here is an example of adding an icon to the button.  Let me know if you have any issues with this.

  ```
<GoogleLogin
        clientId={'658977310896-knrl3gka66fldh83dao2rhgbblmd4un9.apps.googleusercontent.com'}
        callback={responseGoogle}
        offline={false}
  >
    <FontAwesome
      name='google'
    />
    <span> Login with Google</span>
  </GoogleLogin>
```
