### ISSUE TITLE
Missing a Refresh Token 

### ISSUE THREAD

**Issue by rabashani** [anthonyjgrove/react-google-login#144]
I am probably missing something here, Currently I am authenticating my users using the react library, but i am also executing some of the commands using the web-server api (nodejs and php).
so i will need to get access to refresh token.

if i understand the documentation correct,  I can't get access to refresh token from client-side solutions, but only using the web server.

so currently I am using this code.
can i assume that the user is "signed in" to my system? right after clicking the button and getting the response back? or should i do another call to get the user details? 

`                <GoogleLogin
                    clientId={config.googleOAuthClientID}
                    scope=
                        'profile email https://www.googleapis.com/auth/youtube'
                    buttonText="Login"
                    onSuccess={this.successResponse}
                    onFailure={this.errorResponse}
                    onRequest={this.loadingResponse}
                    offline={true}
                    // responseType="id_token permission code"
                    **responseType="code"**
                    isSignedIn
                />
`
  
but with those code, i don't know what is the user's email and name\details
which is a bit awkward

**Comment by atyachin** [comment]
Based on this [thread](https://github.com/google/google-api-php-client/issues/263), I believe that in order to retrieve the refresh token, we need to make a minor change in GoogleLogin.js and pass "prompt=select_account" as a parameter to auth2.grantOfflineAccess.

Here's the suggested change in [Line 75](https://github.com/anthonyjgrove/react-google-login/blob/69fe9286bec7b778e91f3770e898f7f328e6b13f/src/GoogleLogin.js#L75):
`const options = {
        prompt: 'select_account'
      }`



Google API reference: [link](https://developers.google.com/identity/sign-in/web/reference#gapiauth2offlineaccessoptions)

**Comment by BaptWaels** [comment]
You can already give it as prop to the component. It is working fine for me. 

Maybe you've got this problem:
> This can happen if you've already authorized the app once before. The oauth2 server will only ever mint one refresh token at a time, and if you request another access token via the flow it will operate as if you only asked for an access token.
> 
> You can try constructing the flow object with prompt='consent' and see if that fixes it.


I use the component as so to retrieve the code and then transfer it to my API to retrieve access/refresh:

```
<GoogleLogin
                clientId={CLIENT_ID}
                buttonText={messages.googleAuthBtn}
                onSuccess={this.handleGoogleAuthSucess}
                onFailure={this.handleGoogleAuthFailure}
                responseType="code"
                prompt="consent"
                scope="https://www.googleapis.com/auth/calendar"
              />
```

**Comment by rabashani** [comment]
thanks @BaptWaels, my mistake was this line responseType="id_token permission code" 
as you can't use both. it should be either id_token + permission OR code - as the former is client side permission while the latter are server side.
