### ISSUE TITLE
Not a Bug but confused

### ISSUE THREAD

**Issue by ThaddeusAid** [anthonyjgrove/react-google-login#148]
Perhaps I am missing something simple, but I am just not sure how to access my user's group information after gaining the auth token and the the correct scope.

As I have it set up:

I get as part of the response

`scope: "https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/admin.directory.group.member.readonly openid email profile"`

But I am failing at understanding how to get my user's group memberships for the associated domain.

Any help is greatly appreciated.

**Comment by jimmyl02** [comment]
For youtube API this is what I use.

scope="profile email https://www.googleapis.com/auth/youtube.readonly"

Then using the access_token given in the callback,

https://www.googleapis.com/youtube/v3/subscriptions?access_token {YOUR_ACCESS_TOKEN}&part=snippet%2CcontentDetails&mine=true
