### ISSUE TITLE
Disable Login Button until google javascript is loaded

### ISSUE THREAD

**Issue by palamccc** [anthonyjgrove/react-google-login#16]
Loading google javascripts may take a moment or even few seconds in slow connection.
If User clicks login button before that we are getting error,

    Cannot read property 'auth2' of undefined

Can you disable login button, until window.gapi.auth2 is available ? I hope google will have callback on load.
I can also provide pull request, if you are interested.
Thanks for the contribution to community.

**Comment by anthonyjgrove** [comment]
Sure, I will look into this.

**Comment by anthonyjgrove** [comment]
@palamccc Issue should be resolved.  Let me know if you still experience this issue.
