### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by sujanshah** [anthonyjgrove/react-google-login#173]
400. That’s an error.

Error: redirect_uri_mismatch

The JavaScript origin in the request, http://localhost:8080, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/771997706208-p681uron6ej5fdphtkd6nv4ujmsqosos.apps.googleusercontent.com?project=771997706208 to update the authorized JavaScript origins.

**Comment by louie728** [comment]
is there any way to add a wildcard or add through an api?  I have an application that has dynamically created origins origin1.mydomain.com origin2.mydomain.com.
