### ISSUE TITLE
Catch login failure error

### ISSUE THREAD

**Issue by rogchap** [anthonyjgrove/react-google-login#18]
`auth2.signIn()` should catch any errors thrown. e.g when `hostedDomain` does not match an error is thrown, but is not caught in the `callback` function.

Suggestion is to rename `callback` prop to `onSuccess` and add an `onFailure` prop

FYI: Should also rename `cssClass` to `className` to be consistent with the rest of the React.

**Comment by anthonyjgrove** [comment]
From what I can tell `hostedDomain` auth errors are handled within the login popup box, can you give me repo steps?

For `className`  good idea, will make that change with the next release.,

**Comment by rogchap** [comment]
`hostedDomain` auth errors are **not** handled in the popup.
Example with this:

``` javascript
<GoogleLogin
  clientId={oAuthClientId}
  hostedDomain="somedomain.com"
  callback={tryLogin} />
```

You'll get the expected Google Sign In Popup asking for a `somedomain.com` email address, but you can still enter an `@gmail.com` email address instead. This will throw the following error in the app:

```
cb=gapi.loaded_0:51 Uncaught Object {
  accountDomain: undefinedexpectedDomain: "somedomain.com",
  reason: "Account domain does not match hosted_domain specified by gapi.auth2.init.",
  type: "tokenFailed"__proto__: Object(anonymous function) 
@ cb=gapi.loaded_0:51
```

**Comment by anthonyjgrove** [comment]
Okay, I was able to repo it now, I was trying to auth with an account that was already authenticated which just kept taking me back to add another account.  I will add the error handling, thanks for the bug.

**Comment by anthonyjgrove** [comment]
Let me know if 2.5.0 does not fully address this issue.  Thanks again!
