### ISSUE TITLE
HOW to add readonly and plus.me scope 

### ISSUE THREAD

**Issue by Lokendra-rawat** [anthonyjgrove/react-google-login#185]

**Comment by Shrikant9** [comment]
🔔 Bump, is this possible in any way?
I tried adding `scope="profile email https://www.googleapis.com/auth/plus.me"` 
and 
`scope="profile email plus.me"`

But no luck there.

**Comment by ben-foster** [comment]
Same issue here. I'm trying to authorize with multiple scopes at once. I've tried passing the following to the ```scope``` prop:
```js
const scopes = ["https://www.googleapis.com/auth/analytics.readonly", "https://www.googleapis.com/auth/analytics.manage.users"]
```

```js
const scopes = "https://www.googleapis.com/auth/analytics.readonly, https://www.googleapis.com/auth/analytics.manage.users"
```
```js
const scopes = "https://www.googleapis.com/auth/analytics.readonly,https://www.googleapis.com/auth/analytics.manage.users"
```

...and I'm getting errors on all 3. Is there currently any way to authorize multiple scopes at once with react-google-login?

**Comment by anthonyjgrove** [comment]
https://developers.google.com/+/api-shutdown
