### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by shrijan00003** [anthonyjgrove/react-google-login#193]
i have integrated react-google-login with my credentials and when component mounts it is trying to get the uri: 
[https://accounts.google.com/o/oauth2/iframerpc?action=listSessions&client_id=my_id_here&origin=http%3A%2F%2F127.0.0.1%3A8000&scope=openid%20profile%20email&ss_domain=http%3A%2F%2F127.0.0.1%3A8000]
But having error of invalid request 
`{
  "error" : "invalid_request",
  "error_description" : "Permission denied to generate login hint for target domain."
}`

please help

**Comment by anuragaj** [comment]
I am getting the same error. What @shrijan00003 what is the solution

**Comment by shrijan00003** [comment]
@anuragaj make sure your application is configured properly
