### ISSUE TITLE
Google+ Sign-in feature deprecated 

### ISSUE THREAD

**Issue by alcbotta** [anthonyjgrove/react-google-login#200]
First of all, Thank you very much for this library.

A question: 
All Google+ API will be deprecated by the end of January. Does it affect this component?

Kind regards.

**Comment by martinek** [comment]
Some more information about which API's will be deprecated / shutdown.
https://developers.google.com/+/api-shutdown

I would also like to know if any update will be necessary.

**Comment by anthonyjgrove** [comment]
This is uses the Google Client library (https://developers.google.com/api-client-library/javascript/start/start-js) so no reason to believe this component should be affected but the Google+ shutdown (unless you are pulling in Google Plus data).  I am going to update to the latest js file they have in the google client docs to be safe.
