### ISSUE TITLE
Invalid prop buttonText of type object supplied to GoogleLogin, expected string

### ISSUE THREAD

**Issue by lucasdeassis** [anthonyjgrove/react-google-login#208]
When I pass a node to the `buttonText` prop on GoogleLogin, I get the message below:

```
warning.js:35 Warning: Failed prop type: Invalid prop `buttonText` of type `object` supplied to `GoogleLogin`, expected `string`.
    in GoogleLogin (created by GoogleButton)
    in GoogleButton (created by Translate(GoogleButton))
    in Translate(GoogleButton) (created by CheckoutLogin)
    in div (created by CheckoutLogin)
    in div (created by CheckoutLogin)
    in div (created by CheckoutLogin)
    in div (created by CheckoutLogin)
    in CheckoutLogin (created by Translate(CheckoutLogin))
    in Translate(CheckoutLogin)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by Translate(Layout))
    in Translate(Layout) (created by Scene)
    in I18nextProvider (created by Scene)
    in Scene
    in HoneyBadgerErrorBoundary
```

I saw on `GoogleButton.js` source code that on `render()`, if `buttonText` is provided and `children` not, it replaces `children`. 
```
<ButtonContent icon={icon} key={2}>
  {children || buttonText}
</ButtonContent>
```
So, makes more sense to me that `buttonText` should be of type `Proptypes.node` instead of `PropTypes.string`, as GoogleLogin allows me to do something like:

``` 
  <GoogleLogin {...props}
  buttonText={<div className="social__container">
        <div
          className={Classnames(
            'icons--google-sign-in',
          )}
        />
        <div className="social__button__text">{title}</div>
      </div>
    } />
```

**Comment by anthonyjgrove** [comment]
Yeah that makes sense as far as prop types goes.  Maybe just removing buttonText all together might make more sense but don't want break.  Having it in the first place might have been unnecessary over just using children. Ill merge in your fix for now while I think about removing it.

**Comment by lucasdeassis** [comment]
thanks! Got it. I was going to ask that. Maybe if you release a new version (6.0) removing `buttonText`, it will break but accordingly to `semVer` so people will be aware.
