### ISSUE TITLE
Add `onRequest` method

### ISSUE THREAD

**Issue by Connorelsea** [anthonyjgrove/react-google-login#24]
State management libraries like Redux typically process three events in auth sequences similar to `react-google-login`. Any kind of first attempt will emit a `REQUEST` action, which can be used to show a loading symbol or prepare the program to accept auth details. Then a `SUCCESS` or `FAILURE` action will come after.

I would like to add `onRequest` to the component in addition to `onSuccess` and `onFailure` so I can dispatch a request action in Redux.

If you feel that this is an appropriate addition, I can submit a pull request.

        <GoogleLogin
          clientId="*"
          onSuccess={this.props.onLoginSuccess}
          onFailure={this.props.onLoginFailure}
          onRequest={this.props.onLoginRequest}
        />

It would be easy to implement this feature. Simply add onRequest as a prop that accepts a function. Then call this function at the beginning of the `onBtnClick()` method on line 65 of `src/google.js`

**Comment by anthonyjgrove** [comment]
Sounds good, submit a PR and we can go from there!

-Anthony
