### ISSUE TITLE
How to use it with firebase?

### ISSUE THREAD

**Issue by brahmharsh** [anthonyjgrove/react-google-login#253]
I am able to signed in with Google but the signed in users not able to store in firebase authentication. I have used client ID as well as enabled the google sign-in method. 
Do I have to write anything else in the code. Please help.

**Comment by brahmharsh** [comment]
https://stackoverflow.com/questions/58419569/how-to-use-react-google-login-package-with-firebase

**Comment by sangjin42** [comment]
Brahmharsh 

> https://stackoverflow.com/questions/58419569/how-to-use-react-google-login-package-with-firebase

Hello Brahmharsh
There's no page now. 
If you don't mind could you let me know your solution?

**Comment by sangjin42** [comment]
> https://stackoverflow.com/questions/58419569/how-to-use-react-google-login-package-with-firebase

Brahmharsh

https://stackoverflow.com/questions/58419569/how-to-use-react-google-login-package-with-firebase

Hello Brahmharsh
There's no page now.
If you don't mind could you let me know your solution?
