### ISSUE TITLE
Add new prop for "prompt" option

### ISSUE THREAD

**Issue by jazib** [anthonyjgrove/react-google-login#26]
An addition of a new prop setting "prompt" field can be helpful. 
Expected options:
1. none
2. login
3. consent
4. select_account
to be set in [options field of gapi](https://developers.google.com/identity/sign-in/web/reference#googleauthsigninoptions)

**Comment by anthonyjgrove** [comment]
Fixed: 219063bad8d479cd00e2d2bd3eca4e5789515ccb
