### ISSUE TITLE
Convert to a hook

### ISSUE THREAD

**Issue by dacioromero** [anthonyjgrove/react-google-login#263]
Is it possible for this library to be converted to be a hook?

If you remove the render logic it looks like it could pretty easily be a hook.

**Comment by anthonyjgrove** [comment]
https://github.com/asyarb/react-use-googlelogin

**Comment by dacioromero** [comment]
I see that #270 does this and #282 exposes it. Great work!

**Comment by dacioromero** [comment]
#270 #282 accomplishes this, great work!
