### ISSUE TITLE
Logout built in function

### ISSUE THREAD

**Issue by Ethan0007** [anthonyjgrove/react-google-login#285]
Hi,

Is there any built in function to logout the current authenticated user in google?
because right now I see only built in component from react-google-login:

<GoogleLogout
clientId={GOOGLE_CLIENT_ID}
onLogoutSuccess={console.log} />

Thanks.

**Comment by josivan** [comment]
I noticed that in version 5.0.8 hooks are available (to login and logout). But in the NPM the latest version is 5.0.7. When are you (@anthonyjgrove and @erikmjohnson ) planning to update npm repo?

**Comment by elvisguillen** [comment]
PING! I'm really interested in getting access to the signOut function as well from the new useGoogleLogin hook from 5.0.8. Currently running the npm 5.0.7.

I essentially need to sign out users on my onSuccess response callback if that Google account is not associated with any of the users in my app. Currently users just get a white pop up if they signed in with the wrong account, not allowing them to choose a different Google account afterwards.

**Comment by anthonyjgrove** [comment]
exported hooks are published in v5.1.0
