### ISSUE TITLE
Error: "popup_closed_by_user"

### ISSUE THREAD

**Issue by theexplosivegroup** [anthonyjgrove/react-google-login#286]
Hi guys, 

In Google Chrome I am receiving this error when trying to log-in.

Appears to be isolated to Chrome, as other browsers work fine.

Anyone else dealing with this?

**Comment by shubhamraj-appa-curefit** [comment]
HI what was the issue for this i see u have marked it as closed
how did you fix this

**Comment by theexplosivegroup** [comment]
HI there, I honestly can't remember what was causing this. I think either my popup blocker was doing it, or it was trying to open in the same window.
