### ISSUE TITLE
Block third-party cookies error

### ISSUE THREAD

**Issue by Maor44** [anthonyjgrove/react-google-login#294]
when this option is on I can't get the plugin to work. 

I got this error: 

error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"
details: "Cookies are not enabled in current environment."

this option going to be turn on by default (google said not me). is there any solution for it?

thanks.

**Comment by mikeyyyzhao** [comment]
@Maor44 was there a solution to this? We're getting this error on Brave (the browser) but everything seems to work on Chrome

**Comment by itsdarrylnorris** [comment]
I am having the same issue on FF 73.0.1

**Comment by khera-shanu** [comment]
why is this closed?

**Comment by itsdarrylnorris** [comment]
My particular issue was related to FF very strict mode, which did not allow you to do OAUTH in your browser. Changing some FF settings or changing the browser did the trick for me.
