### ISSUE TITLE
Integration with passportjs

### ISSUE THREAD

**Issue by BenjiTheC** [anthonyjgrove/react-google-login#304]
I'm able to get the user info (`id_token`, `access_token`, `profile`, etc) using this library in my react frontend, is there a recommendation of which passportjs is suitable for a use case where the frontend send the tokens to backend and backend can verified itself to google and retrieve user info?

Thanks!

**Comment by jonas060831** [comment]
@BenjiTheC  passport-google-plus-token

**Comment by Danswar** [comment]
@BenjiTheC, I recommend to use https://www.npmjs.com/package/passport-google-id-token.

I tried with a bunch of others passport strategies and this was the only one that work to me. (I also tried passport-google-plus-token)

**Comment by BenjiTheC** [comment]
Turns out it's not the strategy, but the fact that I'm located in mainland China and the GFW stops the code from working. I hosted the code on a GCP App Engine and it's working perfectly.

I'm using https://www.npmjs.com/package/passport-google-id-token
