### ISSUE TITLE
login button is disabled

### ISSUE THREAD

**Issue by AlenToma** [anthonyjgrove/react-google-login#313]
Hi, Im using this script to login to google but the login button is disabled

I dont see any error, or information why this happen any idee here pls help

     <GoogleLogin
                                    disabled={false}
                                    clientId="**********-akj6ujapgd722u0kqaib2lmca3mu71vt.apps.googleusercontent.com"
                                    buttonText="Login"
                                    onSuccess={this.responseGoogle}
                                    onFailure={this.responseGoogle}
                                    cookiePolicy={'single_host_origin'}
                                />

**Comment by madhu131313** [comment]
There might be a reason why it's disabled, responseGoogle prints that, please see what's the error

```
 responseGoogle = (response) => {
  console.log(response);
}
```

**Comment by AlenToma** [comment]
there was no response to log, but i got it to work at last now, you may close this if you want

**Comment by FrozenIce0617** [comment]
Hi @AlenToma 
Please let me know how you fix this issue.
Now I'm facing same kind of problem.

Thanks.

**Comment by AlenToma** [comment]
in google console under `Authorized JavaScript origins` I added https://localhost, And it worked. 

Thats all i did.

**Comment by akshayrathodar** [comment]
> disabled={false}

i have this error tooo please Do Something , button is disable as well as nothing it does no any call in network tab

**Comment by seeck3** [comment]
@AlenToma 

I just added Authorized JavaScript origin, and it's not still working.. =[

**Comment by AlenToma** [comment]
I really don`t know, i just added it and started working on its own.

**Comment by ONUOHA92** [comment]
I have added to my JavaScript Authorized

**Comment by ONUOHA92** [comment]
And is not working

**Comment by nguyendviet** [comment]
I have the same issue.

**Comment by Ishu1998** [comment]
Same Problem here, Button is disabled....

**Comment by RealSlimMahdi** [comment]
same problem here, manual refresh enable the button but at first page load the buttons are disabled (login + logout)

`      <GoogleLogin
        clientId="..."
        fields="first_name,last_name,email,picture"
        onSuccess={responseGoogle}
        onFailure={responseGoogle}
        buttonText="LogIn"
        isSignedIn={true}
        // hostedDomain="gmail.com"
      />`

**Comment by RealSlimMahdi** [comment]
Hi Again,

After inserting this code from google documentation:
in Header:
`<meta
      name="google-signin-client_id"
      content="YOUR CLIENT ID"
    />`

Right after body tag:
`<script src="https://apis.google.com/js/platform.js" async defer></script>`

I do not experience the issue anymore and the buttons are enabled from start.

**Comment by frknbasaran** [comment]
> @AlenToma
> 
> I just added Authorized JavaScript origin, and it's not still working.. =[

Try remove browser cache. It's worked on me.

**Comment by moroz112** [comment]
Hi, guys. Did you find any solution? Got the same issue. Tried all suggestions in comments above(

**Comment by akshayrathodar** [comment]
Bro i don't know what is algorithm behind this google auth but after 2 day
it will works automatically

**Comment by anthonyjgrove** [comment]
Hopefully v5.1.18 should this.  Let me know if it has not.

**Comment by markociglar** [comment]
I got same problem

**Comment by anthonyjgrove** [comment]
@markociglar please provide an example with your props

**Comment by harry100** [comment]
I used the default configurations.
The button is disable hence I cannot click it to view the response causing the error.
Anyone has a working solution. Any Help will be useful thanks.

**Comment by akshayrathodar** [comment]
Bro I don't know how but it will work but after getting this error 3 days
later it will work automatically

**Comment by JeanTak** [comment]
> Hi Again,
> 
> After inserting this code from google documentation:
> in Header:
> `<meta name="google-signin-client_id" content="YOUR CLIENT ID" />`
> 
> Right after body tag:
> `<script src="https://apis.google.com/js/platform.js" async defer></script>`
> 
> I do not experience the issue anymore and the buttons are enabled from start.

Hi anybody tried this? I did the same but still got that issue...

**Comment by fandiahm** [comment]
In my case, it's because the internet connection. 
Open the inspect network, request to : `https://accounts.google.com/o/oauth2/iframe`  failed.

**Comment by rahulshah4994** [comment]
As @fandiahm noted - you need a live internet connection at the time of running the app. If the internet connection isn't working, the button is disabled by default. Very interesting! Let me know if this works for you guys.

**Comment by znwhite** [comment]
Having this issue myself, in a Next.js app. Using default props + my clientId

**Comment by Harmyder** [comment]
I have the same issue. And I'm wondering why do I see the following if I haven't yet clicked on it:

> {message: "Missing required parameter 'client_id'", RK: true, stack: "gapi.auth2.ExternallyVisibleError: Missing require…Pwd_oodKkRT_hYRO1I-9xRcQV4oQ/cb=gapi.loaded_0:1:6"}

**Comment by appledora** [comment]
> > Hi Again,
> > After inserting this code from google documentation:
> > in Header:
> > `<meta name="google-signin-client_id" content="YOUR CLIENT ID" />`
> > Right after body tag:
> > `<script src="https://apis.google.com/js/platform.js" async defer></script>`
> > I do not experience the issue anymore and the buttons are enabled from start.
> 
> Hi anybody tried this? I did the same but still got that issue...

Hello, it worked in my case.

**Comment by lesagi** [comment]
> > > Hi Again,
> > > After inserting this code from google documentation:
> > > in Header:
> > > `<meta name="google-signin-client_id" content="YOUR CLIENT ID" />`
> > > Right after body tag:
> > > `<script src="https://apis.google.com/js/platform.js" async defer></script>`
> > > I do not experience the issue anymore and the buttons are enabled from start.
> > 
> > 
> > Hi anybody tried this? I did the same but still got that issue...
> 
> Hello, it worked in my case.

Hi,
I tried and it didn't work.. how can I append a script tag after the body?

**Comment by lesagi** [comment]
> <meta name="google-signin-client_id" content="YOUR CLIENT ID" />

Hi,
How can you add a script tag after the body? I'm using the starter create-react-app and I edited the index.html file, but the script is not loaded and not shown after the body

**Comment by ariccio** [comment]
Weird. I'm sporadically encountering this on the same device where I'm hitting issue #451 ...

**Comment by stefanylaforest** [comment]
I was getting this error and after clearing your browser cookies it works.

**Comment by aaronkang7** [comment]
Guys I think I figured it out:
change client_id to clientId in our GoogleLogin properties... I did it for fun and it worked :D

**Comment by vinc01100101** [comment]
still getting this error. tried all the suggestions above but unfortunately nothing works :C

**Comment by alexbraga** [comment]
I don't know why is this issue closed if the problem persists. In production, the button only works after a page refresh.

**Comment by pradeepsh2203** [comment]
For me adding `accessType="online"` , resolved the error

**Comment by florianwalther-private** [comment]
Make sure your client_id is correct. This was the issue for me.

**Comment by Axselll** [comment]
make sure you guys have internet connection

**Comment by adarshanand67** [comment]
Read all the comments and tried all the possibilities. This is still not working for me

**Comment by titoadeoye** [comment]
This is still not working. Why is it closed??

**Comment by Abhinav1182** [comment]
> in google console under `Authorized JavaScript origins` I added https://localhost, And it worked.
> 
> Thats all i did.

I have added this and it worked for me in DEV but not working in Production URL
