### ISSUE TITLE
apis.google.com/js/client:platform.js not found

### ISSUE THREAD

**Issue by saidmoya12** [anthonyjgrove/react-google-login#32]
apis.google.com/js/client:platform.js not found issue when I trigger the button

**Comment by anthonyjgrove** [comment]
i am not seeing this issue. Can you provide some more info to repo it.

**Comment by tomtwo** [comment]
I'm seeing this issue when developing on chrome - `//apis.google.com` converts to `chrome-extension://apis.google.com`
