### ISSUE TITLE
Get request before any code runs in react app

### ISSUE THREAD

**Issue by ThahaShahzad** [anthonyjgrove/react-google-login#325]
https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A3000&client_id=xxxxx.apps.googleusercontent.com 401

why does the get happen before everything? were is it called?
 i need to get the client id form dropbox first then use that for the client id but the google login somehow does the get request before the dropbox is initialized how can i put a delay on the client id check

**Comment by Ramprakash333** [comment]
> https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A3000&client_id=xxxxx.apps.googleusercontent.com 401
> 
> why does the get happen before everything? were is it called?
> i need to get the client id form dropbox first then use that for the client id but the google login somehow does the get request before the dropbox is initialized how can i put a delay on the client id check

Facing similar issue. Did you got any workaround for this

**Comment by SimonMillerIO** [comment]
> https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A3000&client_id=xxxxx.apps.googleusercontent.com 401
> 
> why does the get happen before everything? were is it called?
> i need to get the client id form dropbox first then use that for the client id but the google login somehow does the get request before the dropbox is initialized how can i put a delay on the client id check

Facing similar issue. Did you got any workaround for this

**Comment by ThahaShahzad** [comment]
I didn't really find a fix what I did was just have that one variable in environment variable and thankfully client Ids don't really ever change so it was fine.
