### ISSUE TITLE
auto login, even if i set autoLoad to false

### ISSUE THREAD

**Issue by wassimbj** [anthonyjgrove/react-google-login#327]
Hey guys, anyone of you knows whats the solution for this ?
even when i set the autoLoad to false i still get the auto login

**Comment by wassimbj** [comment]
Fixed, sorry for bothering :)

**Comment by ThahaShahzad** [comment]
What was the fix?

**Comment by wassimbj** [comment]
@ThahaShahzad it is not related to this package, it was just a bug in my code, double check your code and you will fix it, and also put the autoLoad to false
