### ISSUE TITLE
Auto-signin does not work for SPA (react-router)

### ISSUE THREAD

**Issue by MichaelGatesDev** [anthonyjgrove/react-google-login#328]
I noticed that the auto-signin does not work for single page applications because the component does not re-render properly when a new path is pushed and the page has **not** refreshed.

https://github.com/anthonyjgrove/react-google-login/blob/master/src/use-google-login.js#L121

In other words, it will only work if the page is refreshed so as to trigger the render for the component.

**Comment by MichaelGatesDev** [comment]
Would be fixed by https://github.com/anthonyjgrove/react-google-login/pull/247

**Comment by anthonyjgrove** [comment]
Can get #247 merged if you want to provide a rebased MR

**Comment by anthonyjgrove** [comment]
released npm v5.1.12

**Comment by DrewHoo** [comment]
FTR this was fixed by #329 for anyone else looking
