### ISSUE TITLE
style parameter not setting backgroundImage

### ISSUE THREAD

**Issue by mattmiddlesworth** [anthonyjgrove/react-google-login#33]
I tried using the style parameter and I couldn't get my image to appear. We originally had this as a static setting this using CSS where it worked. We now want it be inline style set dynamically to be our image server host from our env variables.

```
<GoogleLogin
              clientId={process.env.GOOGLE_ID}
              buttonText="Log in with Google"
              className="btn icon-btn btn-block space-1 signup-login-form__btn-xl btn-large btn-google"
              style={{backgroundImage: `url(${process.env.IMAGE_HOST}Google_-G-_Logo.png)`}}
              onSuccess={this.responseGoogle}
              onFailure={this.responseGoogle}
            />

**Comment by anthonyjgrove** [comment]
write now it is not setup to allow both css and a style.  I will update it to handle your use case.

-Anthony

**Comment by anthonyjgrove** [comment]
@mattmiddlesworth all fixed in newest version, let me know if you have any other issues.

**Comment by mattmiddlesworth** [comment]
This works perfect now, thanks so much.
