### ISSUE TITLE
onRequest is required when using useGoogleLogin

### ISSUE THREAD

**Issue by bennettrogers** [anthonyjgrove/react-google-login#332]
When using the `useGoogleLogin` hook without defining `onRequest` the library throws an error when calling `signIn`. `onRequest()` is called [here](https://github.com/anthonyjgrove/react-google-login/blob/master/src/use-google-login.js#L57).

It seems like either `onRequest` should be checked for existence before being called, or it should be marked as REQUIRED in the docs.

Thanks for this library - it's making an annoying process much easier to implement!

**Comment by dulyts** [comment]
#330 solve this too

**Comment by anthonyjgrove** [comment]
Should be fixed now
