### ISSUE TITLE
onSuccess property is being called at the wrong time

### ISSUE THREAD

**Issue by Steague** [anthonyjgrove/react-google-login#334]
After updating to 5.1.19

Steps to reproduce:
- Click on the `GoogleLogin` component/button.
- Observe the `onSuccess` method is invoked.
- Observe an `undefined` parameter is passed to the `onSuccess` method.
- Observe this happens before the OAuth popup window is displayed or confirmed.

Observed behavior:
`onSuccess` method is called before a successful OAuth flow is complete.
This causes thrown errors if the response parameter is not vetted.

Expected behavior:
`onSuccess` method is only called after a successful OAuth flow is complete.

Workaround:
```js
<GoogleLogin
    onSuccess={(response) => { if (!response) return; ... }}
    ...
/>
```

**Comment by anthonyjgrove** [comment]
Can you provide an example with your props

**Comment by Steague** [comment]
My apologies. I had the incorrect props set up.
