### ISSUE TITLE
Offline access is always requested

### ISSUE THREAD

**Issue by tjunnone** [anthonyjgrove/react-google-login#35]
When using the default component settings, or even when explicitly setting the offline={false} prop, the "X would like to have offline access" permission is always presented to the user in the Google OAuth dialog. Is there any way to get rid of this?

Using version 2.5.8.

**Comment by anthonyjgrove** [comment]
Can you paste your full implementation of the component, I haven't be able to duplicate this.

-Anthony

**Comment by anthonyjgrove** [comment]
Let me know if you can provide more details.
