### ISSUE TITLE
Getting "idpiframe_initialization_failed" in private navigation

### ISSUE THREAD

**Issue by dglsn** [anthonyjgrove/react-google-login#352]
Hi,

In private navigation (with Chrome), Login button stay disabled.

When I logged responseGoogle, I have this error : 
`{error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."}`

Do you know how i could enabled it? I think I have already been able to connect via google in private browsing on other sites

Thanks in advance

**Comment by kobimantzur** [comment]
Happens to me as well.
Tried browsing my website's production URL in private browsing mode (Incognito)
Chrome // 83.0.4103.116
macOS Version 10.15.3 (Build 19D76)

**Comment by enorvaisa** [comment]
I also have this problem with Chrome.
Looks like problem exists on Chrome incognito mode or on browsers where 3rd party cookies are disabled.
More info can be found here: https://developers.google.com/identity/sign-in/web/troubleshooting

**Comment by ninjaasmoke** [comment]
Almost all of my users on Android chrome are facing this problem. The only way to solve it right now is to prompt the user to make an exception for accounts.google.com to allow 3rd party cookies.

**Comment by cetinsert** [comment]
@dglsn @kobimantzur @enorvaisa @ninjaasmoke 
Hi everyone! We might have found a very simple workaround: https://github.com/pwa-builder/PWABuilder/issues/3286#issuecomment-1219798658 (confirmed from multiple websites).
