### ISSUE TITLE
Prevent double click

### ISSUE THREAD

**Issue by Sybio** [anthonyjgrove/react-google-login#36]
Hi @anthonyjgrove, great repo !

Is there a way to prevent double click, - and so, double call to Google - by catching an event object on onRequest() method ?

```javascript
// Prevent new click if loading var is true
<GoogleLogin
    onRequest={(e) => {
        loading &&
        e.preventDefault()
    }}
>
    Sign In with Google
</GoogleLogin>
```

Or by creating a new attribute : 
```javascript
// Disable new click if loading var is true
<GoogleLogin
    disabled={loading}
>
    Sign In with Google
</GoogleLogin>
```

**Comment by anthonyjgrove** [comment]
Are you having this issue on the latest version of the component? Double clicks should be prevented already.

**Comment by anthonyjgrove** [comment]
Never mind, The main issue with implementing this is you have to disable the button when the button is clicked and auth window is open but currently I don't think there is an easy way to detect if the user simply closes the auth window without accepting.  The user would then be left with a disabled button if they wanted to try to authenticate again.

**Comment by anthonyjgrove** [comment]
Gonna close this for now, unless you have some thoughts on how to better implement this.
