### ISSUE TITLE
Asking to enable Cookies when initializing google login in chrome incognito mode

### ISSUE THREAD

**Issue by lakshmikanth-reddy-au2** [anthonyjgrove/react-google-login#361]
Hi,

I have this issue in Chrome browser incognito mode.

In my application When i click on Login a modal will popup like below 
![image](https://user-images.githubusercontent.com/49977739/87943494-c15cc900-cabb-11ea-99b4-53f546e118fb.png)

As soon as popup opens onFailure callback is being called and in responce i am getting error value as "Cookies are not enabled in current environment". Also Google Login button is disabled.

After i close the popup and open again it works fine and Google Login button is enabled.

I want to know why is this behavior and how to eliminate this.

Please help me out with this.

**Comment by aneskurtovic** [comment]
+ 1 same problem here in Incognito mode

**Comment by lakshmikanth-reddy-au2** [comment]
> * 1 same problem here in Incognito mode

Hey @aneskurtovic I just resolved it by just changing one browser settings. You just need to allow cookies for all sited.

Go to settings and search for cookies.

Click on Cookies and other site data and check if "Block third-party cookies in Incognito" is checked or not. If checked uncheck and it and select "Allow all cookies".

This should solve the issue.
