### ISSUE TITLE
Disabled state style

### ISSUE THREAD

**Issue by dominikbulaj** [anthonyjgrove/react-google-login#37]
Hi,

Would be possible to define style(s) for disabled state? E.g. making button semi transparent to notify user that it's not ready to use, yet? 

It would match behavior of keppelen/react-facebook-login: 
https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L181

**Comment by anthonyjgrove** [comment]
I can try to add this in the next few weeks.

**Comment by anthonyjgrove** [comment]
Let me know if this is not what you had in mind.

-Anthony

**Comment by dominikbulaj** [comment]
Doesn't work for me - maybe because I use custom element inside (child) and I was forced to use empty style: 
```javascript
    return <GoogleLogin
      clientId={config.sso.google.clientId}
      buttonText={label}
      onRequest={ssoGoogleRequest}
      onSuccess={this.successGoogleResponse}
      onFailure={this.failureGoogleResponse}
      tag='span'
      style={{}}
    >
      <RaisedButton backgroundColor={'#d14836'} label={label} labelColor="white" style={{ width: '50%' }}/>
    </GoogleLogin>
```

and in your source code I see:
```javascript
    const styleProp = (() => {
      if (style) {
        return style;
      } else if (className) {
        return {};
      }
      return defaultStyle;
    })();
```
And for me it looks like it never reaches `defaultStyle` in this case.

My require of use empty style is just hack to disable initial component styles which breaks my markup.
```javascript
      width: 190,
      paddingTop: 10,
      paddingBottom: 10,
      borderRadius: 2,
``` 
Anyway thanks for your help :)

**Comment by anthonyjgrove** [comment]
Ill take another look today or tomorrow, to make sure that scenario  is covered .

Anthony Grove

**Comment by anthonyjgrove** [comment]
Updated, let me know if this works.

**Comment by dominikbulaj** [comment]
I've created [pull request](https://github.com/anthonyjgrove/react-google-login/pull/40) adjusting disable vs disabled names. See comment there. 

Great job. Thank for your time! 👍

**Comment by dominikbulaj** [comment]
Checked but it fails because for disabled state there is `disabledStyle` setting with `opacity: 0.6` 
It renders component correctly with this style. I think test has to be adjusted. Don't know if should I do it? :)
