### ISSUE TITLE
Authentication doesnot work when used in inapp browser of instagram or facebook.

### ISSUE THREAD

**Issue by harry-dev98** [anthonyjgrove/react-google-login#377]
When tried to login in inappbrowser, popup opens up after filling google credentials, there comes a loading indicator which keeps on rotating. No further activity. Is there anyway to debug the issue in inappbrowser, or any help will be apreciated.
thanks

**Comment by harry-dev98** [comment]
okay i came to this is issue with inapp browsers thankyou m closing the issue

**Comment by giddens9527** [comment]
How do you fix the issue? Having the same issue now.
