### ISSUE TITLE
onSuccess sometimes accidently invoked

### ISSUE THREAD

**Issue by onlyongunz** [anthonyjgrove/react-google-login#39]
Step to reproduce:
1. Make sure you logged in to Google with several accounts
2. Login using `react-google-login`.
3. Remove current logged in token (not the Google one, something like, our program's cookie, etc).
4. Login again using `react-google-login`.
5. After relogin, i monitored the network, onSuccess event are accidently invoked, soonly after i clicked "Login with Google". Logged in using current account.

**Comment by anthonyjgrove** [comment]
Cam you provide the code for your current setup? What props are you using etc?

**Comment by onlyongunz** [comment]
Hang on, i'll post it here...

**Comment by anthonyjgrove** [comment]
Tried duplicating it, but was not able to. Let me know if you can provide me with any more details on how to reproduce it.

**Comment by onlyongunz** [comment]
have you tried it several times? the bug sometime come because the instability of the code... i'm not sure which code is it.

thank you

**Comment by anthonyjgrove** [comment]
Would you be able to setup a jsbin or something similar with the issue reproduced?
