### ISSUE TITLE
how to logout the logged in user

### ISSUE THREAD

**Issue by john1jan** [anthonyjgrove/react-google-login#41]
Is there any method for logout of the logged in user

**Comment by anthonyjgrove** [comment]
Currently there is no built in method to actually handling logging out of the user.  Are you wanting to use google to handle auth state as well.  Currently it is just setup to provide auth token which you can use with your own user database.

**Comment by anthonyjgrove** [comment]
Give me more info on your use case and maybe we can add something for it.

**Comment by cealia** [comment]
I have the same question. I use the auth token provided by the googleLogin api to maintain my own user database. But the question is that, how can users change from one to another, I mean how can one user logout and than another user login?

**Comment by john1jan** [comment]
I am storing the auth token which i get from google. But once the user is logged with one account. He cannot change his google account until user is logged out from gapi

**Comment by TommieEdwardBerry** [comment]
similar problem for me, i want to let the user login, but after he is done with my app,
I want him to hit the log out button.  I need a react-google-logout-component.

**Comment by john1jan** [comment]
Pull request #110 solves the problem
