### ISSUE TITLE
Changes in GAPI v2

### ISSUE THREAD

**Issue by kavithaLK** [anthonyjgrove/react-google-login#42]
Can you please update the component to take in this extra prop: 'fetch_basic_profile'

It is now required to work-around the issue mentioned here: 
https://github.com/google/google-api-javascript-client/issues/266#issuecomment-272302189

Thanks

**Comment by anthonyjgrove** [comment]
ill take a look tomorrow

**Comment by anthonyjgrove** [comment]
LMK if this update does not address what you need.

**Comment by rafi** [comment]
Working great again, thanks.
