### ISSUE TITLE
Getting errors when running the npm command

### ISSUE THREAD

**Issue by aaronjohnsonwsu** [anthonyjgrove/react-google-login#43]
Hey, 

I am trying to add your component to my project but I keep getting errors when running the npm command.

I run: 

`npm install react-google-login`

But get these errors:

`C:\Users\ajohnson\Documents\Workspace\react-sandbox>npm install react-google-login
npm WARN package.json react-sandbox@0.1.0 No repository field.
npm http GET https://registry.npmjs.org/react-google-login
npm http 304 https://registry.npmjs.org/react-google-login
npm http GET https://registry.npmjs.org/types/react
npm http 404 https://registry.npmjs.org/types/react
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'react-google-login'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-google-login"
npm ERR! cwd C:\Users\ajohnson\Documents\Workspace\react-sandbox
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\ajohnson\Documents\Workspace\react-sandbox\npm-debug.log
npm ERR! not ok code 0`

Am I doing something wrong or need to install something else?

Thanks

**Comment by anthonyjgrove** [comment]
Still having this issue? I have never tired this on a Windows machine.  Are you able to npm install other components? I am not seeing any issues on Mac or Linux.
