### ISSUE TITLE
Can't get refresh token

### ISSUE THREAD

**Issue by shaikatzir** [anthonyjgrove/react-google-login#45]
I followed the instructions and used "approvalPermit=force"
```
<GoogleLogin
        clientId={clientId}
        buttonText="Login"
        approvalPrompt="force"
        onSuccess={this.onSuccess}
        onFailure={this.onFailure}
/>
```
But it doesn't actually prompt for approval and therefore doesn't return a refresh token.
I checked the API documentation ([Google API](https://developers.google.com/identity/sign-in/web/reference#googleauthsignin)), and it doesn't seems to support the "permit" option. Instead, they offer [reloadAuthResponse](https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse) in order to get a "refreshed" token.
Any other option?

**Comment by anthonyjgrove** [comment]
That was adding by another person, from what it looks like it stopped working when they switched to 2.0.  Think you will have to use the prompt prop now `prompt='consent'`.  Let me know if that doesn't work. I will update the docs and remove that prop.

https://github.com/google/oauth2client/issues/453
