### ISSUE TITLE
Use as link wrapper around another button component

### ISSUE THREAD

**Issue by Arrow7000** [anthonyjgrove/react-google-login#46]
Thanks for making this, it's been a huge help! 

Would it be possible to either: 

- Expose a separate component, or
- Allow the insertion of a child component into the current component

Either of which would allow the functionality of the login button to be exposed, without having to use the actual button element that this component creates. Currently if I want to use my own button I would need to override the existing styles of this component, which means I don't have full control over the styles, and there could be some styles I'd forget to override. Using my own elements as the button body would make aesthetic control much easier.

The idea being that I could use this component like this:

```
<GoogleLogin
    clientId="xxxxxxx"
    buttonText="Login"
    onSuccess={func}
    onFailure={func}>
    <MyButton />
</GoogleLogin>
```

which would not change the way `<MyButton />` looks but would give it all the functionality of its parent component. 

Would this be at all possible? If the owner or maintainers like this idea I'd be more than happy to have a go at creating a pull request myself.

**Comment by anthonyjgrove** [comment]
Hi @Arrow7000 You should be able to do this.  Just set the tag prop to the desired type, change the className of the GoogleLogin component to whatever you need it to be and add your button as a child .

Example below should do what you want.

`<GoogleLogin
    clientId="xxxxxxx"
    onSuccess={func}
    onFailure={func}>
    className="col medium-12"
    tag="div"
 >
    <MyButton />
</GoogleLogin>
`

Let me know if you have any questions

**Comment by Arrow7000** [comment]
Ok, thank you. Now the only minor problem I have is that you need to add a `className` to the component to override its default class. This means having to make up a random className, like `"null"`, which is messy and not a guaranteed empty CSS class. 

Could there be a setting to simply disable all existing styles, something like `noStyle={true}` that would simply render an empty, unstyled `div`?
