### ISSUE TITLE
Refresh the google auth manually through code

### ISSUE THREAD

**Issue by nickyoung87** [anthonyjgrove/react-google-login#466]
I am having an issue with finding out how to refresh the Google auth through code. The main problem is that after the 1 hour session has timed out then I start to get errors. 

I have set `isSignedIn` to true, but this doesn't really help me since I am on a dashboard type of page and want it to refresh when an api call fails (using axios interceptor to do this). I would love to just try a refresh on the google auth when there is a 401 returned. I am already successfully doing this with my API and a 1 hour JWT, so it seems reasonable to use the same method for the google auth refresh. This kind of works, but according to other comments on the internet I should just do `gapi.something.refreshToken` basically, but this doesn't work with me because the `gapi` is not available when I try to call it (probably due to the 401 errors causing the rest of the script not to load or something)

I was hoping this plugin would just kind of handle that for me, but it seems not. Any ideas I could try?

Thanks!

**Comment by elias-naffaa** [comment]
Hello, did you find any solution?

**Comment by natashagigcasters** [comment]
```
export const refreshTokenSetup = (result) => {
    let refreshTiming = (result.tokenObj.expires_in || 3600 - 5 * 60) * 1000;
    
    const refreshToken = async () => {
        const newAuthRes = await result.reloadAuthResponse();
        refreshTiming = (newAuthRes.expires_in || 3600 - 5 * 60) * 1000;
        // Save new Token --> newAuthRes.access_token
        console.log(`New Authentication Result: ${newAuthRes}`);
        console.log(`New Authentication Token: ${newAuthRes.idToken}`);
        setTimeout(refreshToken, refreshTiming);
    }
    setTimeout(refreshToken, refreshTiming);
    // Still need to deal with the user refreshing the page:
    //https://github.com/anthonyjgrove/react-google-login/issues/175#issuecomment-636499112
}
```

**Comment by elias-naffaa** [comment]
Thank you, where do I place this code exactly? And what should be passed as (result)?

**Comment by nickyoung87** [comment]
I created my own hook using this code snippet as a base, so thank you @natashagigcasters 

The real problem I have though is that this still doesn't fix it on a page refresh. I am able to do it after a login using the result object there. Is there a way to get that same object to persist over a page refresh?

Thanks again!

**Comment by natashagigcasters** [comment]
I believe you will have to store it as something like a cookie or window.localStorage, so the state persists.

**Comment by nickyoung87** [comment]
Yeah so I think I just got this working. I basically set up an axios interceptor to run and then call the custom hook from the interceptor once the gapi object is loaded back in. 

I still think this is something the the package should make a lot easier to handle, but it seems my issue is solved for now.

Thanks for the help!
