### ISSUE TITLE
onFailure triggering on render

### ISSUE THREAD

**Issue by marcosdipaolo** [anthonyjgrove/react-google-login#474]
As soon as the `GoogleLogin` components render, the `onFailre` callback gets triggered, probably because it's trying to login before time and of course it fails. Did anyone had that problem?

**Comment by marcosdipaolo** [comment]
The incognito window triggers the `Cookies are not enabled in current environment.` error

**Comment by nitin41** [comment]
Hi, I'm getting this issue. How can i resolved this?
