### ISSUE TITLE
Custom styles are not shown on button

### ISSUE THREAD

**Issue by sammce** [anthonyjgrove/react-google-login#484]
[Pull request link](https://github.com/anthonyjgrove/react-google-login/pull/483)

## Problem

I was trying to customise the `GoogleLogin` button's styles, and found out that this is not possible. As any programmer would, I decided to fork the repo and do it myself. 

Upon completion, I ran the test suite and saw that it's intended for the styles not to work?

This is the message I got when i ran `npm test`:
<img width="678" alt="Screenshot 2021-09-25 at 16 31 33" src="https://user-images.githubusercontent.com/78268167/134778956-b0ab432a-926f-4ff2-955e-9b9b48ce8822.png">

This is despite a custom style being set in the tests, as shown below:
### tests/google-login.test.js
Line 98, in test suite "With custom class and custom style":
```js
describe('With custom class and custom style', () => {
  const className = 'test-class'
  const style = { color: 'red' }
  const props = {
    onSuccess() {},
    ...
```

Essentially, there is custom styles being set, yet they are not expected to be set on the rendered button.
This was the root of my problem, and I don't understand why this would be the intended behaviour. Feel free to correct me if there is a valid reason

## Fixes
Below are the fixes that I made to my repo:
### src/google-login.js

Line 19, in props destructuring:
```diff
...
disabledStyle,
+ style,
buttonText,
...
```

Line 85, after `initialStyles` definition:
```diff
 ...
 fontWeight: "500",
   fontFamily: "Roboto, sans-serif",
 };

+ if (style) {
+   Object.keys(style).forEach(key => {
+       initialStyle[key] = style[key])
+     };
+ }

const hoveredStyle = {
  cursor: "pointer",
  opacity: 0.9,
};
```

### __test__/__snapshots__/google-login.test.js.snap
Line 111, in "Google Login With custom class and custom style has inline styles 1" snapshot:
```diff
- "color": "rgba(0, 0, 0, .54)",
+ "color": "red",
```

Line: 137, in "Google Login With custom class and custom style render the button 1" snapshot:
```diff
- "color": "rgba(0, 0, 0, .54)",
+ "color": "red",
```

## Result

With these amendments, the following is now possible:
<img width="466" alt="Screenshot 2021-09-25 at 19 25 43" src="https://user-images.githubusercontent.com/78268167/134782504-fa343c5b-9b11-4d2c-98fc-611140ee6e71.png">

### Before
<img width="323" alt="Screenshot 2021-09-25 at 17 33 41" src="https://user-images.githubusercontent.com/78268167/134780463-756d6b99-5674-45b8-ab02-78fbe9004b37.png">

### After
<img width="323" alt="Screenshot 2021-09-25 at 17 33 08" src="https://user-images.githubusercontent.com/78268167/134780469-5b30d52b-b212-474d-b207-96523baed771.png">

**Comment by domdomegg** [comment]
Duplicate of https://github.com/anthonyjgrove/react-google-login/issues/201?

**Comment by sammce** [comment]
@domdomegg 

Apologies, didn't see it when I was looking for an existing issue. Closing this one in favour of the existing one.
