### ISSUE TITLE
Empty given_name and family_name

### ISSUE THREAD

**Issue by vcarel** [anthonyjgrove/react-google-login#50]
Before I could decode given_name and family_name from the id_token. Now those fields are not included anymore.

Is it a regression ?

**Comment by vcarel** [comment]
Well, I don't know if Google changed their API or if the default scope has changed, but the answer is to force the scope to

    scope='openid email profile'

**Comment by anthonyjgrove** [comment]
will be fixed with next release.

**Comment by afshin-hoseini** [comment]
I'm facing the same issue, even with all `openid email profile` scopes :(
