### ISSUE TITLE
Issue with some users on specific computers

### ISSUE THREAD

**Issue by tonioss22** [anthonyjgrove/react-google-login#515]
Hi everyone, 

i'm experiencing issues with some users trying to connect to my application. Some users can't access the application but only on some computers and it seems to affect the whole computer (clearing cache or changing browser does not work). The weird thing is that it does not return an error either. It simply opens the google tab authenticating them, closes it, and nothing, making it quite hard to debug.

So my thinking now is either they failed 2FA (if so, is it possible for them to try again) or maybe the migration to google identity services is affecting them would be odd but i thought i'd try it, but i haven't been successful in implementing it so far (weird origins issue).

If anyone has any ideas that would be great!
Thanks

**Comment by DillonStreator** [comment]
Experiencing the same problem. Ours is related to an issue created on the gapi javascript client https://github.com/google/google-api-javascript-client/issues/812

Side note, the origin issue might be related to https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid
> When you perform local tests or development, you must add both http://localhost and http://localhost:<port_number> to the Authorized JavaScript origins box.

**Comment by tonioss22** [comment]
Thanks Dillon, seems it was the issue with my origin, i had the address with port but not just the address aswell. Odd that i need to have both for the new method. I'll atleast have the new method integrated into my app, we'll see if this one causes issues for the users.

**Comment by HairulDev** [comment]
Thanks, Dillon
I have same issues but still error
Have any solutions ?
