### ISSUE TITLE
Usage Login for multiple scopes on a single page

### ISSUE THREAD

**Issue by JimVercoelen** [anthonyjgrove/react-google-login#52]
Hi,

I am trying to manage a login for different scopes on a single page.

For example; login for google analytics, adwords and search console.

I added 3 GoogleLogin component, all with there own scope, but when I click on one of the buttons it will refer to the same scope.

So I am wondering, the way the GoogleLogin component work, if it's even possible.

**components**
![image](https://cloud.githubusercontent.com/assets/13642402/23699292/db2b9bf0-03ee-11e7-8b29-5be0b8c6161b.png)

**UI**
![image](https://cloud.githubusercontent.com/assets/13642402/23699274/cae6d804-03ee-11e7-9f22-825891d0df3b.png)

**Always the same, no matter which button is clicked**
![image](https://cloud.githubusercontent.com/assets/13642402/23699328/fee18258-03ee-11e7-83e6-14948c29c7a3.png)

**Comment by eliranamar** [comment]
i also encountered this problem, did you found a solution for this?

**Comment by advance512** [comment]
This is what we ended up creating:
https://github.com/Selectom/react-google-authorize
