### ISSUE TITLE
gapi client not loading

### ISSUE THREAD

**Issue by deconstructionalism** [anthonyjgrove/react-google-login#57]
Hi,

This package has worked swimmingly for me in the past, but has recently stopped working as it does not load gapi in the window, such that the following:

**index.js(31)**
``` js
      window.gapi.load('auth2', () => {
```
**returns this error:**
```
Uncaught TypeError: Cannot read property 'load' of undefined
    at HTMLScriptElement.<anonymous> (google-login.js:1)
```

I've also tried using the module in a test boilerplate project and it still has this issue. The script is inserting itself before the first script element in `document.scripts` but it's not loading. Any ideas?

**Comment by anthonyjgrove** [comment]
What version are you using, and when did it stop working?  Does it still do
this with an older version?

**Comment by deconstructionalism** [comment]
v 2.8.5. It looks like I was on v 2.8.2 when I started. Let me try a rollback..

**Comment by deconstructionalism** [comment]
So the rollback didn't help. But here's something odd: the button works just fine in an incognito window. I tried clearing my history in the browser, and now it works. Not sure how browser history could possibly be hindering an non-local client-side script from loading.

**Comment by deconstructionalism** [comment]
It was the Disconnect extension. All good.

**Comment by GrandathePanda** [comment]
In my case I have no extensions enabled that would interfere, and I am having the same issue where gapi is not loading and disabling the login button. It only happens on mac, I am running ubuntu on my desktop and have verified that window.gapi is loading correctly there and I can use the login button as intended in my application.

**Comment by GrandathePanda** [comment]
I was able to circumvent it by by including gapi in my html

`<script src="https://apis.google.com/js/platform.js?onload=onLoadCallback" async defer></script>`

But it seems like you may have some async issue down there with react componentDidMount (where it looks like its breaking) firing before gapi has been added.
