### ISSUE TITLE
Possible to open the Google Sign In redirect url in the same tab?

### ISSUE THREAD

**Issue by sidmitra** [anthonyjgrove/react-google-login#58]
Is it possible to not launch a pop-up but instead redirect to Google in the same browser tab? I tried looking at the Google Sign-In docs as well to see if there was something to toggle, but doesn't seem to mention this.

**Comment by gnhuy91** [comment]
https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2initparams

check `ux_mode`

**Comment by anthonyjgrove** [comment]
Added in 2.8.6

**Comment by sidmitra** [comment]
Thanks for the quick fix. I just tested the new uxMode param. Here're a few issues/notes

```
<GoogleLogin
    buttonText="Google Login"
    clientId={GOOGLE_CLIENT_ID}
    offline={true}
    onFailure={this.responseGoogle}
    onSuccess={this.responseGoogle}
    uxMode="redirect"
    redirectUri={window.location.href}  />
```

- I'm using `window.location.href ` since i need the absolute url with the scheme. Otherwise google throws an error. Also obviously google needs a full url now to redirect.

- The new [README.md](https://github.com/anthonyjgrove/react-google-login/commit/69444bcfcf03a2f22b47deba2fe5ed3ce09824c0#diff-04c6e90faac2675aa89e2176d2eec7d8R67) says 

> The default redirect_uri is the current URL stripped of query parameters and hash fragment.

But that doesn't seem to be the case. If you use uxMode="redirect" but without redirectUri, it still uses "popup".

-  **Issue**: The onFailure/onSuccess are required parameters, but for with uxMode="redirect" it seems the method is called with response as ` {message: "Redirecting to IDP."}` and not with the code.

- Also using only `uxMode` and `redirectUri` the google login redirect does work. After the above message saying `Redirecting to IDP` in the end it does re-direct/re-render(not sure) but with the code etc in the hash fragment.

- I tried adding `responseType="code"` but still doesn't, in case the google changes the redirect with query params. But no change in the behaviour.

I haven't been able to make it work yet. Perhaps i'm doing something wrong. Will explore some more later and report back. Any further information might be really helpful.

**Comment by sidmitra** [comment]
i still couldn't make this work with the latest issue. It defaults to `popup` 

Also find a related issue on the google api client

https://github.com/google/google-api-javascript-client/issues/352

**Comment by Jayiitb** [comment]
@sidmitra Did u find any solution to this?

**Comment by sidmitra** [comment]
@Jayiitb Unfortunately i couldn't get it to work and but i haven't kept up on this since then. Will try to debug some more if i find some time in the next week or so.

**Comment by Jayiitb** [comment]
@sidmitra Thankyou.
I used iframe with talkerjs to get my job done. I was facing the issue of putting multiple subdomains in google console for gauth.

**Comment by BakulTessell** [comment]
@Jayiitb 
Can you share a sample code how you did it?
I also have a requirement of adding Google login on subdomains.
