### ISSUE TITLE
Supply a login_hint

### ISSUE THREAD

**Issue by gausie** [anthonyjgrove/react-google-login#6]
It would be good if we could supply a `loginHint` parameter to autofill an email address in the popup.

**Comment by anthonyjgrove** [comment]
Sounds good, I will add it this weekend.

**Comment by gausie** [comment]
Amazing! Thank you! I tried myself but couldn't find where to add it (since all the documentation I can find includes it in `gapi.authorize`, so looking forward to seeing how you solve this. I know it's almost certainly just a case of bad docs from Google.

**Comment by anthonyjgrove** [comment]
@gausie Should be good to go with v2.1.2.  Let me know if you have any other requests.
