### ISSUE TITLE
apis.google.com/js/client:platform.js script loads every time component is shown

### ISSUE THREAD

**Issue by jerryslaw** [anthonyjgrove/react-google-login#60]
<pre>
<script id="google-login" src="//apis.google.com/js/client:platform.js" gapi_processed="true"></script>
</pre>

I'm using google login button within my custom stateless component. Every time I enter my login subpage, new script is added to DOM.

<pre>
import React from 'react';
import GoogleLogin from 'react-google-login';
import { RaisedButton } from 'material-ui';

const GoogleLoginButton = ({ clientId, userLoginSuccess, userLoginFailure }) => (
    < GoogleLogin
        clientId={clientId}
        onSuccess={response =>
            userLoginSuccess({ token: response.tokenId })
        }
        onFailure={userLoginFailure} >

        < RaisedButton
            label="Login with google"
            fullWidth
            backgroundColor="#dd4b39"
            labelColor="#fff"
        />

    < /GoogleLogin>
);

export default GoogleLoginButton;
</pre>

**Comment by anthonyjgrove** [comment]
They kind of have to have their own unless you want it to use a global one you add to your header.  Is that something you want to be able to do?

**Comment by TomPradat** [comment]
Maybe we could remove the script tag in ComponentWillUnmount or check if the script already exist in ComponentDidMount ?

**Comment by Teomik129** [comment]
Simple workaround if anybody stumbles upon this issue:
```javascript
import GoogleLogin from "react-google-login";

class Login extends GoogleLogin {
  componentWillUnmount() {
    const el = document.querySelector("#google-login");
    el.parentNode.removeChild(el);
  }
}
```
