### ISSUE TITLE
Constantly closing login window

### ISSUE THREAD

**Issue by 7h3w4rd0c70r** [anthonyjgrove/react-google-login#62]
Hi guys, I'm implementing react-google-login to my app and it seems there's a problem somewhere in library. Here is my code:

**_layoutDumb.jsx**
```
import React from 'react';
import { Route, Link } from 'react-router-dom';
import { Container, Segment, Button, Input, Icon } from 'semantic-ui-react';
import GoogleLogin from 'react-google-login';

import _appSmart from 'smart/_app.jsx';

export default (props) => {
    return (
        <div>
            <Route exact path='/' render={() => {
                return (
                    <div className='_ login form'>
                        <GoogleLogin
                            clientId='714689519066-v5g1o9hehsg1kko7jgpdrre7kojlahi1.apps.googleusercontent.com'
                            onSuccess={props.googleResponse}
                            onFailure={props.googleResponse}
                            autoLoad={true}
                            style={{}}
                            className='ui google plus large button' >
                            <Icon name='google' /> Přihlásit
                        </GoogleLogin>
                    </div>
                );
            }} />
            <Route path='/app' component={_appSmart} />
        </div>
    );
}
```
**_layoutSmart.jsx**
```
import React from 'react';
import update from 'react-addons-update';

import _layoutDumb from 'dumb/_layout.jsx';

export default class extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            googleResponse: (response) => { console.log(response); }
        };
    }

    render() {
        return (
            _layoutDumb(this.state)
        );
    }
}
```

I'm able to login within the popup login window and grant application permission to get user data/info and then the window automatically closes and I get an error `Object {error: "popup_closed_by_user"}`. Since then I get this exact same error every time I click on login button.
Is it a problem of library?

**Comment by 7h3w4rd0c70r** [comment]
So, I've just solved the issues. Problem was, origin url was not allowed, but instead of getting not valid origin error, the window auto closed and I got popup closed by user error.

**Comment by camslaz** [comment]
I am having the same issue. I have origin url correctly setup, after I login and grant permissions the windows closes and I receive `{error: "popup_closed_by_user"}`

**Comment by anthonyjgrove** [comment]
@camslaz can you paste in how you have the component setup?

**Comment by 1755** [comment]
I have the same error.

Here is my configuration:
google-login@2.8.9
`
<GoogleLoginComponent
                clientId="17197425356-c7v22c3kasiir0vjllj5g6sl1gsf07v8.apps.googleusercontent.com"
                buttonText="G+"
                className="google-login"
                autoLoad={true}
                onSuccess={this.onGoogleResponse}
                onFailure={this.onGoogleFailure}
            />
`

Every time a popup window close momentaly with error `{error: "popup_closed_by_user"}` after I've loggined in the Google

**Comment by 1755** [comment]
I've found that this error arise when google chrome blocks popup window

**Comment by shishircc** [comment]
@1755 did you find any solution for this ?

**Comment by 1755** [comment]
@shishircc It was caused because AdBlok(or Google Chrome) has blocked popups

**Comment by thakurinbox** [comment]
Add Authorized JavaScript origins in the following order if you are using localhost : 

![screen shot 2017-07-17 at 8 32 33 am](https://user-images.githubusercontent.com/8243530/28254553-6c180886-6acb-11e7-850f-ce57ed5a34c0.png)

**Comment by umerrauf6** [comment]
> same error.
> 
> Here is my configuration:

tried this .still getting same error

**Comment by utsavvasoya8585** [comment]
> So, I've just solved the issues. Problem was, origin url was not allowed, but instead of getting not valid origin error, the window auto closed and I got popup closed by user error.

Hey i have also got same erroe 
Can you help me to solve this error

**Comment by utsavvasoya8585** [comment]
> So, I've just solved the issues. Problem was, origin url was not allowed, but instead of getting not valid origin error, the window auto closed and I got popup closed by user error.

Hey i have also got same erroe 
Can you help me to solve this error
