### ISSUE TITLE
Log In not working

### ISSUE THREAD

**Issue by michaelryancaputo** [anthonyjgrove/react-google-login#63]
For some reason all of a sudden log in using this component has stopped this morning. I see that they are deprecating webview logins today, however, I took a peek at the code and it doesn't seem to be using webviews.

Steps to reproduce:
1- pull this repo
2- install it
3- run `npm run start`
4- try logging in via google

The behaviour i'm seeing is the pop up window shows a 500 error message. Closing sends a "modal window closed" error message to the `onFailure` callback.

**Comment by scandinaro** [comment]
Same here

**Comment by michaelryancaputo** [comment]
I've confirmed that my client ID works with this component: https://github.com/kennetpostigo/react-google-login-component

**Comment by scandinaro** [comment]
@ michaelryancaputo  I just get `Uncaught Object {error: "popup_closed_by_user"}` and the `console.log` within `responseGoogle` is never called.

**Comment by scandinaro** [comment]
@michaelryancaputo Actually, the `react-google-login-component` is working for me now.  Thanks!

**Comment by trenthogan** [comment]
I have been having the same problem this morning.

**Comment by pedrofernandezm** [comment]
I'm experiencing the same problem

**Comment by erlinis** [comment]
Same problem here !

**Comment by weihuali0509** [comment]
I am seeing the same problem as well :(

**Comment by modosc** [comment]
i'm looking into it now.

**Comment by weihuali0509** [comment]
@modosc does this solve the issue?
https://github.com/google/google-api-javascript-client/issues/291

**Comment by modosc** [comment]
it's part of it yes, i'll have the pr up in a few minutes.

**Comment by modosc** [comment]
see #64

**Comment by trenthogan** [comment]
@modosc Looking at your code. What was the problem exactly ?

**Comment by anthonyjgrove** [comment]
published PR to NPM hopefully that fixes it.

**Comment by trenthogan** [comment]
@anthonyjgrove You should make a new semver tag after the fix so we can update package.json to only use versions after the fix. https://docs.npmjs.com/getting-started/publishing-npm-packages
See the Updating the package part ☝️

**Comment by holyxiaoxin** [comment]
@anthonyjgrove can you publish your PR to npm please? Thanks.

**Comment by AlphaDork** [comment]
`npm update -f` pulled the updates in for me! Works great - Thanks!

**Comment by michaelryancaputo** [comment]
I agree, this warrants a new semver tag.

**Comment by michaelryancaputo** [comment]
Yeah... I'm still getting the previous version with running `yarn` and having to force with the `npm update -f` command, I can't put this into production (or even staging for that matter) without a semver.

**Comment by lenin-interware** [comment]
I only need to do:

> $ npm update
> react-base@0.1.0 my-react-app
> └── react-google-login@2.8.7

An it updates without problems.

I confirm that the update fixes the problem! **It works like a charm!!**

**Comment by adamrmelnyk** [comment]
It's a little weird that in master we have 2.8.6 https://github.com/anthonyjgrove/react-google-login/blob/master/package.json#L3
but it's 2.8.7 in npm?

**Comment by michaelryancaputo** [comment]
Hmm, must not have committed the changes?

**Comment by anthonyjgrove** [comment]
I am not currently using this in any of my projects at the moment. Are any of you interested in being added as a collaborators to help me maintain this package?

**Comment by trenthogan** [comment]
@anthonyjgrove Sure
