### ISSUE TITLE
responseType is not being passed

### ISSUE THREAD

**Issue by imtmh** [anthonyjgrove/react-google-login#65]
responseType is there in the props; but i dont see it is mapped to the params.

**Comment by anthonyjgrove** [comment]
Looks like it got removed with the merge that fixed changes google made to their API. @modosc any comments?

**Comment by anthonyjgrove** [comment]
should be fixed in 2.8.8

**Comment by modosc** [comment]
Yeah, I only allows in options that were specified in the docs - I added a link above each section to the google description of those configs and the allowed options. It looked liked some opts
from other places (response type was one of them iirc) were being passed on.

**Comment by modosc** [comment]
as an update: my fix was initially just combing through the api calls and removing invalid options - i lucked into the actual fix while doing this.

but if you look at the docs for the 3 api methods this code uses, none of them support `responseType`:

https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2clientconfig
https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2offlineaccessoptions
https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2signinoptions

what _does_ support that is the confusingly named [authorize](https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2authorizeparams-callback) method - there's a huge warning there not to confuse that with the above api.

if `responseType` is having any effect right now i'm guessing it's accidental and may be yanked out of the api and suddenly result in a 500 (basically what happened with `postmessage` and this original issue)
