### ISSUE TITLE
500 error raised please help

### ISSUE THREAD

**Issue by wapjude** [anthonyjgrove/react-google-login#67]

**Comment by anthonyjgrove** [comment]
Can you post your component setup

**Comment by anthonyjgrove** [comment]
and what version of the component you are using

**Comment by wapjude** [comment]
2.8.8

**Comment by wapjude** [comment]
i hope thats the latest version

**Comment by anthonyjgrove** [comment]
thank, please post your component setup as well.

**Comment by wapjude** [comment]
`<GoogleLogin
                clientId="431470566305-9cq7t4b1cmhotj34knrepm2qupl5lXXXX.apps.googleusercontent.com"
                buttonText="Login"
                onSuccess={this.responseGoogle}
                onFailure={this.responseGoogle}
               />`

**Comment by wapjude** [comment]
only works when i pass the redirectUri as props but on authentication it never go back to the url but reload on the popup page and never returns any response

**Comment by anthonyjgrove** [comment]
Have you tried not including the redirectUri?  Also there is no redirectUrl int he code you posted.

**Comment by wapjude** [comment]
When I don't include the redirecturi it shows error 500 using postmessage as redirect url

**Comment by anthonyjgrove** [comment]
postmessage default was remove at v2.8.7.  Try removing your npm modules and reinstalling them and make sure version you are using is 2.8.8

**Comment by wapjude** [comment]
Nope you still have it in the dist/Google-login.js file on version 2.8.8 have just Installed it on a new app it's still there but not in src/index.js

**Comment by anthonyjgrove** [comment]
ah i must have forgot to rebuild the dist.  I will do that now with 2.8.9.

Thanks!

**Comment by anthonyjgrove** [comment]
Let me know if that fixed it.

**Comment by wapjude** [comment]
fixed. working perfectly
