### ISSUE TITLE
Add fallback element?

### ISSUE THREAD

**Issue by franvarney** [anthonyjgrove/react-google-login#7]
I was trying to use this component and with my implementation, no element gets selected here:
https://github.com/anthonyjgrove/react-google-login/blob/master/src/google.js#L32

Adding a fallback fixes the problem:
`const element = d.getElementsByTagName(s)[0] || document.body`

Do you have any opinions about this (fallback or `document.body`)? I can submit a PR.

**Comment by anthonyjgrove** [comment]
How are you adding the component to the document without a <script> tag?  It finds the script tag in the document and adds the Google API JavaScript file above it so it is available on the global object.

**Comment by franvarney** [comment]
I am using webpack + html-webpack-plugin to inject the app script tag into a html template

**Comment by franvarney** [comment]
I don't see how this fix/change will hurt since currently if there happens to be no script tag, it's going to break anyway. I forked this repo to play around and instead of my above suggestion, I did:

```
if (fjs) fjs.parentNode.insertBefore(js, fjs);
else d.body.appendChild(js);
```

This would follow best practices since script should be just before the closing body tag.

**Comment by anthonyjgrove** [comment]
It should work no problem with webpack + html-webpack-plugin, can you link me to your setup?  I guess the problem I see with this change is the google js file could end up after your js which could cause an error.

**Comment by franvarney** [comment]
The project is private but I am using this boilerplate https://github.com/franvarney/react-boilerplate and here is the deployed project (which is basically nothing right now) http://kultivclient-79970.onmodulus.net which has the if/else statement implemented.

**Comment by anthonyjgrove** [comment]
The main issue with that fix is there is still no garuntee it is going to be placed before your main js file. I am open to addressing it but I don't think that is the best way to fix it.  Either way after playing with the boiler plate, I think something weird is happening when you are using the template option of  html-webpack-plugin and it is over writing your script tag as it doesn't even appear in the source code.   
I was able to get it to work in your boiler plate by replacing the following line in your routes file:
```
render(routes, document.getElementById('root'))
```
with:
```
const domMount = document.createElement('div');
document.body.appendChild(domMount);
render(routes, domMount);
```

**Comment by franvarney** [comment]
I played around more and found an issue with my boilerplate...index.html has the `#root` div as a self-closing when it shouldn't be (despite the code still working aside from your component). 

But I also found this project that is having the same issue I was having:  https://github.com/cdock1029/juno-fullstack/blob/326184cd2065320c23d864a6a3bb4f0ec1fa6f5f/src/app.js#L14 

So I was playing around with your code and found that just doing `d.body.appendChild(js)` without the `insertBefore` still works  (since you are concerned about the ordering). This is the output (and you can check the link above again):

<img width="1159" alt="screen shot 2016-07-14 at 9 36 47 am" src="https://cloud.githubusercontent.com/assets/5891549/16842546/da233400-49ab-11e6-853f-adb547ad2609.png">

As a result, I still don't think it would be a bad idea to have a fallback. As an alternative, you could also not inject the script and have people link it themselves.

**Comment by anthonyjgrove** [comment]
I think I will have to close this until I get a use case for it.  Off the top of my head the only way react can even create the button in an html document is if there is a script tag adding the react application code to the code.   For your case you were over writing the script tags at the bottom of the document by making the mounting div a self closing.  I am happy to look into this again with another use case that I might not be considering.
-Anthony
