### ISSUE TITLE
Accept style from css file

### ISSUE THREAD

**Issue by hqt** [anthonyjgrove/react-google-login#71]
I'm using [React-facebook-login](https://github.com/keppelen/react-facebook-login). This library allows me to define css class, so I can make css in css file. I think this will be better than create style object in code and embedded to component.

**Comment by MaxOrelus** [comment]
I agree with @hqt. It would be really nice if you could add the standard props that regular component have (`css`, `className`). At the moment I have to do some hacky code to manipulate this button to my liking.

Thank you for this great component. It really is plug and play.

**Comment by anthonyjgrove** [comment]
Not sure what you mean, you can add classes from your own ccss to className on the component.
