### ISSUE TITLE
Looking for someone to help manage repo

### ISSUE THREAD

**Issue by anthonyjgrove** [anthonyjgrove/react-google-login#77]
Looking for someone to help manage repo, I do not use this component currently so it is hard to keep up to date with the latest API changes.  Anyone interested in helping me review PRs and issues?

**Comment by aaio** [comment]
I'd love to help out :)

**Comment by ojab** [comment]
Cannot help here, but thanks for you work, it's really appreciated.

**Comment by john1jan** [comment]
@anthonyjgrove I will be happy to help

**Comment by wapjude** [comment]
i'll love to help

**Comment by anthonyjgrove** [comment]
@aaio @john1jan @wapjude 

I invited all 3 of you to be collaborators.  Please take a look at the open issues and PRs.

**Comment by john1jan** [comment]
Sure,,looking in to issues

**Comment by johntran** [comment]
@anthonyjgrove I'm using this repo at work and I would love to help maintain this.

**Comment by anthonyjgrove** [comment]
@johntran  added to the repo.

**Comment by theman0123** [comment]
I'd like to help out.

**Comment by anthonyjgrove** [comment]
@theman0123 sent you an invite link
