### ISSUE TITLE
Component triggers immediately onSuccess

### ISSUE THREAD

**Issue by Stefano-Sega** [anthonyjgrove/react-google-login#79]
Since I updated RGL to the latest release with a simple instance of the component:

`
<GoogleLogin
                        clientId="GoogleClientId"
                        onSuccess={this.responseGoogle}
                        buttonText="GMail Login"
                        className="user-login-register-socials-buttons-google" />
`

... the "onSuccess" callback triggers immediately once the component is rendered using the previously saved credentials, and so the user is logged in immediately.

How to prevent this?
It use not to work this way before the latest release

Version: 2.9.1
Thanks

**Comment by anthonyjgrove** [comment]
fixed
