### ISSUE TITLE
onRequest and onSuccess get called automatically

### ISSUE THREAD

**Issue by mohit-github** [anthonyjgrove/react-google-login#81]
I am rendering the react google login component in a login modal and as soon as the modal opens, the onRequest and onSuccess methods get called automatically.

 Here's my config:
`const googleApi = {
  clientId: <client_id>
}`

`class SocialAuth extends React.Component{`

    `requestGoogleAuth = () => {
        console.log("Start Google Auth")
     }`

     `successResponseGoogle = (googleUser) => {
         console.log(googleUser)
     }`

    `errorResponseGoogle = (response) => {
        console.log(response);
     }`

`render(){`
    `return(`
     `<GoogleLogin`
        `clientId={ googleApi.clientId }`
        `buttonText="Login"`
        `onRequest={ this.requestGoogleAuth }`
        `onSuccess={ this.successResponseGoogle }`
        `onFailure={ this.errorResponseGoogle }`
        `offline={false}`
        `className="socialAuthBtn googleAuthBtn"`
      `>`
        `<span className="fa fa-google"></span>`
        `<span className=""> Google</span>`
      `</GoogleLogin>`
   ` )`
  `}`

**Comment by mroova89** [comment]
I've got the same problem. My Google SignIn button is placed in modal too. Only if my login-modal becomes visible, Google is trying to auto login. My config:

`<GoogleLogin
                          clientId={getConfig().auth.google.clientId}
                          onSuccess={this.googleResponseSuccess}
                          onFailure={this.googleResponseFail}
                          className="btn btn-danger btn-social btn-social-gp fa fa-google-plus w-100"
                          scope="email profile"
                          buttonText="Google"
                          responseType="code"
                          autoLoad={false}
                          prompt="consent"
                      />`
Any ideas why?

**Comment by john1jan** [comment]
@mohit-github did you bind those methods in constructor ?

this.requestGoogleAuth = this. requestGoogleAuth.bind(this);
this. successResponseGoogle = this. successResponseGoogle.bind(this);
this. errorResponseGoogle = this. errorResponseGoogle.bind(this);

**Comment by vvicario** [comment]
I have a similar issue. I have my GoogleLogin button in a header, but it doesn't auto login. 
Pleas if you have any idea
This is my code:



`const GoogleLoginButton = hh(class GoogleLoginButton extends Component {

  constructor(props) {
    super(props);
    this.state = {
      googleButton: null,
    };
    this.onSuccess = this.onSuccess.bind(this);
    this.errorResponseGoogle = this.errorResponseGoogle.bind(this);
    this.onRequest = this.onRequest.bind(this);
  }

  componentDidMount() {
    this.getGoogleConfig();
  }

  getGoogleConfig() {
    const googleButton = h(GoogleLogin, {
      clientId: this.props.clientId,
      buttonText: "Sign In",
      onSuccess: this.onSuccess,
      onRequest: this.onRequest,
      onFailure: this.errorResponseGoogle,
      offline: false
    });
    this.setState(prev => {
      prev.googleButton = googleButton;
      return prev;
    })
  }
  onRequest = () => {
    console.log("Start Google Auth")
  }

  onSuccess = (googleUser) => {
    const token = googleUser.getAuthResponse().id_token;
    this.props.onSuccess(token);
  }
  errorResponseGoogle = (response) => {
    console.log(response);
  }
  render() {
    return this.state.googleButton;
  }
});
export default GoogleLoginButton;`
