### ISSUE TITLE
Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by michaelryancaputo** [anthonyjgrove/react-google-login#86]
I'm getting an error `Can only update a mounted or mounting component` from this line being called in the componentDidMount lifecycle method: https://github.com/anthonyjgrove/react-google-login/blob/master/src/index.js#L35-L37

It seems to only come up when the user is already logged in (user login state is hydrated by cookies into redux).

I guess the `window.gapi.load` method waits for gapi to be loaded and this is why the button is disabled. Is there any other way of doing this?

**Comment by irth** [comment]
I've got the same issue

**Comment by anthonyjgrove** [comment]
@michaelryancaputo @irth can one of you provide some example code?

**Comment by michaelryancaputo** [comment]
Thanks for your attention.

I've started to build a webpackbin with this, however, it will take me some time to finish;

https://www.webpackbin.com/bins/-KvSXA25XHu1AavTwlez

**Comment by jabacchetta** [comment]
The problem here is that setState is being called after the library loads — which can happen after the component has already unmounted. Therefore the code is attempting to set the state of an unmounted component.

**Comment by michaelryancaputo** [comment]
Thank you.

**Comment by anthonyjgrove** [comment]
fix published in 3.0.4.

**Comment by michaelryancaputo** [comment]
Thank you!
