### ISSUE TITLE
Windows phone Login

### ISSUE THREAD

**Issue by pinchuque** [anthonyjgrove/react-google-login#91]
I'm getting error on windows phone, when i use react-google-login 

 {"description":"Unspecified error.","number":-2147467259,"stack":"Error: Unspecified error.\n at QD.prototype.open (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:41:226)\n at rl (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:60:232)\n at pP (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:88:6)\n at qY (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:84:362)\n at Anonymous function (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:85:221)\n at _.C (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_0:54:297)\n at jF.prototype.W2 (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ru.dJpaV4JTWOc.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCN40Weyqf3jAajreKbeDBTHdpV3Mg/cb=gapi.loaded_1:85:29)\n at value (http://ru.jokespace.org/main.44b73d0a834b9991266c.js:40:556135)\n at r (http://ru.jokespace.org/main.44b73d0a834b9991266c.js:14:24855)\n at a (http://ru.jokespace.org/main.44b73d0a834b9991266c.js:14:20962)"} 

Can you help me ?

**Comment by anthonyjgrove** [comment]
I dont have access to a windows phone and since they are  no-longer made I am going to close this.
