### ISSUE TITLE
how get user data like name, email, etc.

### ISSUE THREAD

**Issue by EmmanuelSkapple** [anthonyjgrove/react-google-login#92]
I need get the gender and the birthdate, but I cant :(

**Comment by john1jan** [comment]
For getting name and email. Just use profileObject in the success callback

`console.log("profileObj",WE.Zi.profileObj);`

The object will be like this
```
profileObj:{
	emai:"email@gmail.com"
	familyName:"Francis"
	givenName:"John"
	googleId:"11604*******67403"
	imageUrl:"image url"
	name:"John Francis"
}
```

**Comment by john1jan** [comment]
For getting gender and birthday you need to add some additional scopes
