### ISSUE TITLE
a stupid question

### ISSUE THREAD

**Issue by noob9527** [anthonyjgrove/react-google-login#93]
hello guys, I'm new to React.
May I ask why use IIFE in componentDidMount method? 

I've tried to Google it but found nothing.
Can someone explain that for me? or just give me a link.

```
  componentDidMount() {
    const { clientId, cookiePolicy, loginHint, hostedDomain, autoLoad, isSignedIn, fetchBasicProfile, redirectUri, discoveryDocs, onFailure, uxMode } = this.props;
    ((d, s, id, cb) => {
      const element = d.getElementsByTagName(s)[0];
      const fjs = element;
      let js = element;
      js = d.createElement(s);
      js.id = id;
      js.src = '//apis.google.com/js/client:platform.js';
      fjs.parentNode.insertBefore(js, fjs);
      js.onload = cb;
    })(document, 'script', 'google-login', () => {
...
```

**Comment by john1jan** [comment]
because you can access document object only after component is mounted

**Comment by noob9527** [comment]
@john1jan Oh, I'm so sorry.My English is bad too.
I meant to ask why use IIFE, not "why put that in the componentDidMount method".

anyway, thank you for your reply.

**Comment by john1jan** [comment]
its just a way of using the methods
