### ISSUE TITLE
How you can get the gender and the birthday?

### ISSUE THREAD

**Issue by EmmanuelSkapple** [anthonyjgrove/react-google-login#98]
Hi I have about 1 month looking like crazy, how to get the gender and birthday, I used google guides
but I cant and change the scope like this 
https://www.googleapis.com/auth/userinfo.email 
https://www.googleapis.com/auth/userinfo.profile 
https://www.googleapis.com/auth/plus.login
 https://www.googleapis.com/auth/plus.me

but not working, you can help me please, I need deliver my school work in a week, please

**Comment by john1jan** [comment]
Can you try adding birthday scope in the component.

**scope : https://www.googleapis.com/auth/user.birthday.read**

```
<GoogleLogin
        clientId='*******i.apps.googleusercontent.com'
        scope='https://www.googleapis.com/auth/user.birthday.read'
        onSuccess={success}
        onFailure={error}
        onRequest={loading}
        offline={false}
        approvalPrompt="force"
        responseType="id_token"
        isSignedIn={true}
        // disabled
        // prompt="consent"
        // className='button'
        // style={{ color: 'red' }}
    >
      <span>Birthday</span>
    </GoogleLogin>

```
After the adding the scope . When you sign in , google will ask permission to read your birthday information.

![screen shot 2017-08-24 at 7 08 09 pm](https://user-images.githubusercontent.com/4264813/29668979-9a447724-88ff-11e7-84c4-8517eb4f2ab3.png)

After you click on **Allow**. You will get a success callback. In the success callback response object. Get the **googleId** value and hit another api to get the birthday info of the logged in user

You can get the api details from this doc

https://developers.google.com/+/web/api/rest/latest/people/get
![screen shot 2017-08-24 at 6 56 01 pm](https://user-images.githubusercontent.com/4264813/29669131-185488c0-8900-11e7-96d8-d0f5b22c9fe2.png)


**​user googleId in place of userId**
​
I got the birthday using this api.
![screen shot 2017-08-24 at 6 56 14 pm](https://user-images.githubusercontent.com/4264813/29669143-20a3f484-8900-11e7-8403-9fcc0707fa62.png)


​
Important Note: For getting the birthday information of the user. The user birthday info should be public in his google plus profile 

To make your birthday public. go to https://aboutme.google.com/
![screen shot 2017-08-24 at 6 52 23 pm](https://user-images.githubusercontent.com/4264813/29669161-30a4807e-8900-11e7-8769-fb2dc2187780.png)
![screen shot 2017-08-24 at 6 53 15 pm](https://user-images.githubusercontent.com/4264813/29669164-30b4838e-8900-11e7-8137-f12e3059f117.png)

Go to "Gender Date and More"  Section


​



By default it will not show the year of birth. If you want year of birth. You should click on edit icon and check "Show year"

![screen shot 2017-08-24 at 6 54 01 pm](https://user-images.githubusercontent.com/4264813/29669177-38c45e14-8900-11e7-9f5d-6fd6b52e979c.png)

Got insights from [https://stackoverflow.com/questions/19612357/retrieving-date-of-birth-and-marital-status-with-google-oauth-api]Retrieving date of birth and marital status with Google OAuth API

**Comment by john1jan** [comment]
Hope this helps. try this out and let me know if it works for you. Closing it for now

**Comment by Parveshdhull** [comment]
You only told about date of birth not about gender .... please tell me how can I get gender when gender is private.

**Comment by ningo-agilityio** [comment]
I got this response after trying to calling that api:
```
{
    "error": {
        "errors": [
            {
                "domain": "usageLimits",
                "reason": "dailyLimitExceededUnreg",
                "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
                "extendedHelp": "https://code.google.com/apis/console"
            }
        ],
        "code": 403,
        "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
    }
}
```
Could you help to check?

**Comment by mketanv1** [comment]
@ningo-agilityio, because your google signup API request is over that wise error is thrown.
